// Baza przepisów - Książka Kucharska
// © Marek Zettel — wszelkie prawa zastrzeżone.
// Treść przepisów nie jest objęta licencją MIT, która dotyczy kodu aplikacji.
// Pola: id, title, category (obiady|salatki|desery|ciasta),
//       age (dzieci|mlodzi|dorosli|seniorzy), time (minuty), ingredients[], steps[]
//
// Grupy wiekowe:
//   dzieci    -> 3-18 lat
//   mlodzi    -> 20-40 lat
//   dorosli   -> 40-60 lat
//   seniorzy  -> 60+ lat

const RECIPES = [
  // ====================== OBIADY (50) ======================
  { id: 1, title: "Spaghetti bolognese", category: "obiady", age: "dzieci", time: 40,
    ingredients: ["400 g makaronu spaghetti", "500 g mięsa mielonego wołowego", "1 cebula", "2 ząbki czosnku", "500 ml passaty pomidorowej", "2 łyżki oliwy", "sól, pieprz, oregano", "ser parmezan do posypania"],
    steps: ["Cebulę i czosnek pokrój i podsmaż na oliwie.", "Dodaj mięso mielone i smaż do zrumienienia.", "Wlej passatę, dopraw i duś 20 minut.", "Ugotuj makaron al dente.", "Podawaj makaron z sosem i startym parmezanem."] },
  { id: 2, title: "Domowe nuggetsy z kurczaka", category: "obiady", age: "dzieci", time: 30,
    ingredients: ["500 g piersi z kurczaka", "2 jajka", "100 g bułki tartej", "50 g mąki", "sól, pieprz, papryka słodka", "olej do smażenia"],
    steps: ["Kurczaka pokrój na kawałki i dopraw.", "Obtocz w mące, jajku i bułce tartej.", "Smaż na rozgrzanym oleju na złoto z obu stron.", "Osącz na papierowym ręczniku."] },
  { id: 3, title: "Zupa pomidorowa z makaronem", category: "obiady", age: "dzieci", time: 35,
    ingredients: ["1 l bulionu warzywnego", "500 ml passaty", "150 g makaronu", "2 łyżki śmietany", "sól, pieprz, cukier"],
    steps: ["Zagotuj bulion i wlej passatę.", "Dopraw solą, pieprzem i szczyptą cukru.", "Ugotuj makaron osobno.", "Zahartuj śmietanę i wmieszaj do zupy.", "Podawaj zupę z makaronem."] },
  { id: 4, title: "Rosół z makaronem", category: "obiady", age: "dzieci", time: 90,
    ingredients: ["1 kg mięsa drobiowego", "2 marchewki", "1 pietruszka", "kawałek selera", "1 cebula", "natka pietruszki", "sól, pieprz, ziele angielskie", "200 g makaronu nitki"],
    steps: ["Mięso zalej zimną wodą i zagotuj, zbierz szumowiny.", "Dodaj warzywa i przyprawy.", "Gotuj na małym ogniu około 1,5 godziny.", "Ugotuj makaron osobno.", "Podawaj rosół z makaronem i natką."] },
  { id: 5, title: "Pierogi ruskie", category: "obiady", age: "dzieci", time: 70,
    ingredients: ["500 g mąki", "1 jajko", "250 ml ciepłej wody", "500 g ziemniaków", "250 g twarogu", "1 cebula", "sól, pieprz"],
    steps: ["Zagnieć ciasto z mąki, jajka i wody.", "Ugotuj ziemniaki, połącz z twarogiem i podsmażoną cebulą.", "Rozwałkuj ciasto i wycinaj krążki.", "Nakładaj farsz i zlepiaj pierogi.", "Gotuj w osolonej wodzie do wypłynięcia."] },
  { id: 6, title: "Naleśniki z mięsem", category: "obiady", age: "dzieci", time: 50,
    ingredients: ["300 g mąki", "2 jajka", "500 ml mleka", "400 g mięsa mielonego", "1 cebula", "sól, pieprz", "olej"],
    steps: ["Zmiksuj mąkę, jajka i mleko na ciasto naleśnikowe.", "Usmaż cienkie naleśniki.", "Podsmaż mięso z cebulą i dopraw.", "Nałóż farsz, zwiń naleśniki.", "Podsmaż na patelni przed podaniem."] },
  { id: 7, title: "Leniwe pierogi", category: "obiady", age: "dzieci", time: 30,
    ingredients: ["500 g twarogu", "2 jajka", "150 g mąki", "2 łyżki cukru", "szczypta soli", "masło i bułka tarta do podania"],
    steps: ["Twaróg zmiel i połącz z jajkami, cukrem i mąką.", "Uformuj wałki i pokrój na kawałki.", "Gotuj w osolonej wodzie do wypłynięcia.", "Podawaj z masłem i podrumienioną bułką tartą."] },
  { id: 8, title: "Klopsiki w sosie pomidorowym", category: "obiady", age: "dzieci", time: 45,
    ingredients: ["500 g mięsa mielonego", "1 jajko", "3 łyżki bułki tartej", "1 cebula", "500 ml passaty", "sól, pieprz", "ryż do podania"],
    steps: ["Wymieszaj mięso z jajkiem, bułką i cebulą.", "Uformuj klopsiki.", "Obsmaż je na patelni.", "Zalej passatą i duś 20 minut.", "Podawaj z ugotowanym ryżem."] },
  { id: 9, title: "Makaron z serem zapiekany", category: "obiady", age: "dzieci", time: 40,
    ingredients: ["400 g makaronu", "300 g sera żółtego", "400 ml mleka", "2 łyżki masła", "2 łyżki mąki", "sól, pieprz, gałka muszkatołowa"],
    steps: ["Ugotuj makaron al dente.", "Z masła i mąki zrób zasmażkę, wlej mleko.", "Dodaj większość startego sera i dopraw na sos.", "Połącz z makaronem, przełóż do naczynia.", "Posyp serem i zapiekaj 15 minut."] },
  { id: 10, title: "Placki ziemniaczane", category: "obiady", age: "dzieci", time: 40,
    ingredients: ["1 kg ziemniaków", "1 cebula", "1 jajko", "3 łyżki mąki", "sól, pieprz", "olej do smażenia"],
    steps: ["Zetrzyj ziemniaki i cebulę na tarce.", "Odsącz nadmiar płynu.", "Dodaj jajko, mąkę i przyprawy.", "Smaż placki na rozgrzanym oleju na złoto.", "Osącz na ręczniku papierowym."] },
  { id: 11, title: "Zapiekanka makaronowa z szynką", category: "obiady", age: "dzieci", time: 45,
    ingredients: ["400 g makaronu", "200 g szynki", "300 ml śmietany 18%", "2 jajka", "150 g sera żółtego", "sól, pieprz"],
    steps: ["Ugotuj makaron.", "Pokrój szynkę w kostkę.", "Wymieszaj śmietanę z jajkami i przyprawami.", "Połącz makaron, szynkę i sos w naczyniu.", "Posyp serem i zapiekaj 20 minut w 180°C."] },
  { id: 12, title: "Risotto z warzywami", category: "obiady", age: "dzieci", time: 35,
    ingredients: ["300 g ryżu arborio", "1 l bulionu warzywnego", "1 cukinia", "1 marchewka", "1 cebula", "50 g parmezanu", "2 łyżki masła"],
    steps: ["Podsmaż cebulę i pokrojone warzywa.", "Dodaj ryż i chwilę podsmaż.", "Stopniowo dolewaj bulion, mieszając.", "Gotuj aż ryż będzie miękki.", "Dodaj masło i parmezan, wymieszaj."] },
  { id: 13, title: "Kurczak w panierce z ziemniakami", category: "obiady", age: "dzieci", time: 40,
    ingredients: ["500 g piersi z kurczaka", "2 jajka", "bułka tarta", "mąka", "800 g ziemniaków", "sól, pieprz", "olej"],
    steps: ["Filety rozbij i dopraw.", "Panieruj w mące, jajku i bułce tartej.", "Smaż na złoto z obu stron.", "Ziemniaki ugotuj i podaj z masłem.", "Serwuj z ulubioną surówką."] },
  { id: 14, title: "Kurczak teriyaki z ryżem", category: "obiady", age: "mlodzi", time: 35,
    ingredients: ["500 g piersi z kurczaka", "4 łyżki sosu sojowego", "2 łyżki miodu", "1 łyżka octu ryżowego", "1 ząbek czosnku", "imbir", "300 g ryżu", "sezam"],
    steps: ["Kurczaka pokrój w paski.", "Wymieszaj sos sojowy, miód, ocet, czosnek i imbir.", "Smaż kurczaka, dodaj sos i zredukuj.", "Ugotuj ryż.", "Podawaj kurczaka z ryżem, posyp sezamem."] },
  { id: 15, title: "Makaron carbonara", category: "obiady", age: "mlodzi", time: 25,
    ingredients: ["400 g spaghetti", "150 g boczku", "3 żółtka", "1 jajko", "80 g pecorino", "pieprz czarny", "sól"],
    steps: ["Ugotuj makaron al dente.", "Podsmaż boczek na chrupko.", "Roztrzep żółtka z jajkiem i serem.", "Połącz gorący makaron z boczkiem, zdejmij z ognia.", "Dodaj masę jajeczną, mieszaj szybko, dopraw pieprzem."] },
  { id: 16, title: "Chili con carne", category: "obiady", age: "mlodzi", time: 50,
    ingredients: ["500 g mięsa mielonego", "1 puszka fasoli czerwonej", "1 puszka kukurydzy", "500 ml passaty", "1 cebula", "2 ząbki czosnku", "chili, kmin rzymski, papryka"],
    steps: ["Podsmaż cebulę i czosnek.", "Dodaj mięso i smaż do zrumienienia.", "Wlej passatę i przyprawy.", "Dodaj odsączoną fasolę i kukurydzę.", "Duś 30 minut na małym ogniu."] },
  { id: 17, title: "Tacos z wołowiną", category: "obiady", age: "mlodzi", time: 30,
    ingredients: ["8 tortilli kukurydzianych", "400 g mięsa wołowego mielonego", "1 cebula", "przyprawa taco", "pomidor", "sałata", "ser tarty", "śmietana"],
    steps: ["Podsmaż cebulę i mięso z przyprawą taco.", "Pokrój pomidora i sałatę.", "Podgrzej tortille.", "Nałóż mięso, warzywa i ser.", "Polej śmietaną i zwiń."] },
  { id: 18, title: "Curry z kurczakiem", category: "obiady", age: "mlodzi", time: 40,
    ingredients: ["500 g kurczaka", "400 ml mleka kokosowego", "2 łyżki pasty curry", "1 cebula", "2 ząbki czosnku", "imbir", "ryż", "kolendra"],
    steps: ["Podsmaż cebulę, czosnek i imbir.", "Dodaj kurczaka i obsmaż.", "Dodaj pastę curry i mleko kokosowe.", "Duś 20 minut.", "Podawaj z ryżem i kolendrą."] },
  { id: 19, title: "Stir-fry z tofu i warzywami", category: "obiady", age: "mlodzi", time: 25,
    ingredients: ["300 g tofu", "1 papryka", "1 marchewka", "garść brokułów", "3 łyżki sosu sojowego", "1 łyżka oleju sezamowego", "czosnek, imbir", "makaron ryżowy"],
    steps: ["Tofu pokrój i podsmaż na chrupko.", "Dodaj pokrojone warzywa i smaż krótko.", "Dolej sos sojowy i olej sezamowy.", "Ugotuj makaron ryżowy.", "Połącz wszystko i podawaj."] },
  { id: 20, title: "Burgery wołowe", category: "obiady", age: "mlodzi", time: 30,
    ingredients: ["500 g mięsa wołowego mielonego", "4 bułki burgerowe", "1 cebula", "sałata", "pomidor", "ogórek konserwowy", "ser cheddar", "sól, pieprz"],
    steps: ["Z mięsa uformuj kotlety i dopraw.", "Smaż 3-4 minuty z każdej strony.", "Podgrzej bułki.", "Złóż burgera: sałata, kotlet, ser, warzywa.", "Podawaj z frytkami."] },
  { id: 21, title: "Pad thai", category: "obiady", age: "mlodzi", time: 35,
    ingredients: ["250 g makaronu ryżowego", "200 g krewetek", "2 jajka", "kiełki fasoli", "3 łyżki sosu rybnego", "2 łyżki tamaryndowca", "orzeszki ziemne", "limonka"],
    steps: ["Namocz makaron ryżowy.", "Podsmaż krewetki, odłóż.", "Wbij jajka i wymieszaj.", "Dodaj makaron, sos rybny i tamaryndowiec.", "Wmieszaj kiełki, posyp orzeszkami i limonką."] },
  { id: 22, title: "Gulasz wieprzowy", category: "obiady", age: "mlodzi", time: 70,
    ingredients: ["700 g łopatki wieprzowej", "2 cebule", "2 papryki", "500 ml bulionu", "2 łyżki koncentratu pomidorowego", "papryka słodka, majeranek", "mąka do zagęszczenia"],
    steps: ["Mięso pokrój w kostkę i obsmaż.", "Dodaj cebulę i paprykę.", "Wlej bulion i koncentrat, dopraw.", "Duś około godziny.", "Zagęść mąką i podawaj z kaszą."] },
  { id: 23, title: "Łosoś pieczony z warzywami", category: "obiady", age: "mlodzi", time: 35,
    ingredients: ["4 filety łososia", "1 cukinia", "1 papryka", "garść pomidorków", "oliwa", "cytryna", "sól, pieprz, zioła"],
    steps: ["Warzywa pokrój i ułóż na blasze.", "Skrop oliwą i dopraw.", "Ułóż łososia, skrop cytryną.", "Piecz w 200°C około 20 minut.", "Podawaj od razu."] },
  { id: 24, title: "Lasagne", category: "obiady", age: "mlodzi", time: 70,
    ingredients: ["płaty lasagne", "500 g mięsa mielonego", "500 ml passaty", "1 cebula", "beszamel (mleko, masło, mąka)", "200 g sera", "zioła włoskie"],
    steps: ["Przygotuj sos mięsny z passatą.", "Ugotuj beszamel.", "Układaj warstwy: sos, płaty, beszamel.", "Posyp serem.", "Piecz 40 minut w 180°C."] },
  { id: 25, title: "Pizza domowa", category: "obiady", age: "mlodzi", time: 60,
    ingredients: ["300 g mąki", "7 g drożdży", "180 ml ciepłej wody", "passata", "mozzarella", "ulubione dodatki", "oliwa, oregano"],
    steps: ["Zagnieć ciasto i odstaw do wyrośnięcia.", "Rozwałkuj placek.", "Posmaruj passatą i dodaj ser.", "Dołóż ulubione składniki.", "Piecz w 250°C około 12 minut."] },
  { id: 26, title: "Burrito z fasolą", category: "obiady", age: "mlodzi", time: 30,
    ingredients: ["4 duże tortille", "1 puszka fasoli czerwonej", "200 g ryżu", "1 puszka kukurydzy", "ser tarty", "salsa", "awokado"],
    steps: ["Ugotuj ryż.", "Podgrzej fasolę z przyprawami.", "Na tortilli ułóż ryż, fasolę i kukurydzę.", "Dodaj ser, salsę i awokado.", "Zawiń ciasno burrito."] },
  { id: 27, title: "Schabowy z ziemniakami i kapustą", category: "obiady", age: "dorosli", time: 50,
    ingredients: ["4 plastry schabu", "2 jajka", "bułka tarta", "mąka", "800 g ziemniaków", "500 g kapusty kiszonej", "sól, pieprz", "olej"],
    steps: ["Schab rozbij i dopraw.", "Panieruj w mące, jajku i bułce.", "Smaż na złoto z obu stron.", "Ziemniaki ugotuj.", "Kapustę poddusz i podawaj razem."] },
  { id: 28, title: "Gołąbki w sosie pomidorowym", category: "obiady", age: "dorosli", time: 90,
    ingredients: ["1 główka kapusty", "500 g mięsa mielonego", "150 g ryżu", "1 cebula", "500 ml passaty", "sól, pieprz"],
    steps: ["Sparz liście kapusty.", "Wymieszaj mięso z podgotowanym ryżem i cebulą.", "Zawiń farsz w liście.", "Ułóż w garnku, zalej passatą.", "Duś około godziny."] },
  { id: 29, title: "Bigos", category: "obiady", age: "dorosli", time: 120,
    ingredients: ["1 kg kapusty kiszonej", "500 g kapusty białej", "400 g kiełbasy", "300 g mięsa wieprzowego", "grzyby suszone", "śliwki suszone", "liść laurowy, ziele angielskie"],
    steps: ["Poddusz obie kapusty.", "Dodaj pokrojone mięso i kiełbasę.", "Dorzuć namoczone grzyby i śliwki.", "Dopraw i duś kilka godzin.", "Najlepszy odgrzewany następnego dnia."] },
  { id: 30, title: "Pieczeń wołowa", category: "obiady", age: "dorosli", time: 120,
    ingredients: ["1 kg wołowiny", "2 cebule", "2 marchewki", "500 ml bulionu", "2 ząbki czosnku", "tymianek, rozmaryn", "sól, pieprz", "oliwa"],
    steps: ["Mięso natrzyj przyprawami i obsmaż.", "Dodaj warzywa i czosnek.", "Wlej bulion.", "Piecz pod przykryciem w 160°C około 2 godzin.", "Sos zredukuj i podawaj."] },
  { id: 31, title: "Pierś z indyka w sosie grzybowym", category: "obiady", age: "dorosli", time: 45,
    ingredients: ["600 g piersi z indyka", "300 g pieczarek", "1 cebula", "200 ml śmietany", "bulion", "sól, pieprz, natka"],
    steps: ["Indyka pokrój i obsmaż.", "Dodaj cebulę i pieczarki.", "Wlej trochę bulionu i duś.", "Dodaj śmietanę i dopraw.", "Posyp natką i podawaj z kaszą."] },
  { id: 32, title: "Zupa grochowa", category: "obiady", age: "dorosli", time: 90,
    ingredients: ["400 g grochu łuskanego", "300 g boczku wędzonego", "2 marchewki", "1 cebula", "2 ziemniaki", "majeranek, czosnek", "sól, pieprz"],
    steps: ["Namocz groch przez noc.", "Ugotuj groch z boczkiem.", "Dodaj pokrojone warzywa.", "Gotuj do miękkości.", "Dopraw majerankiem i czosnkiem."] },
  { id: 33, title: "Żurek", category: "obiady", age: "dorosli", time: 60,
    ingredients: ["500 ml zakwasu na żur", "300 g białej kiełbasy", "200 g boczku", "1 l bulionu", "2 ziemniaki", "czosnek, majeranek", "jajka na twardo"],
    steps: ["Ugotuj bulion z boczkiem i kiełbasą.", "Dodaj pokrojone ziemniaki.", "Wlej zakwas i zagotuj.", "Dopraw czosnkiem i majerankiem.", "Podawaj z połówką jajka."] },
  { id: 34, title: "Pieczony dorsz z warzywami", category: "obiady", age: "dorosli", time: 40,
    ingredients: ["4 filety dorsza", "1 cytryna", "2 marchewki", "1 por", "oliwa", "koperek", "sól, pieprz"],
    steps: ["Filety skrop cytryną i dopraw.", "Warzywa pokrój i ułóż na blasze.", "Połóż rybę na warzywach.", "Skrop oliwą.", "Piecz 25 minut w 190°C, posyp koperkiem."] },
  { id: 35, title: "Kaczka pieczona z jabłkami", category: "obiady", age: "dorosli", time: 150,
    ingredients: ["1 kaczka", "4 jabłka", "majeranek", "czosnek", "sól, pieprz", "miód", "kasza gryczana do podania"],
    steps: ["Kaczkę natrzyj przyprawami i czosnkiem.", "Nafaszeruj jabłkami.", "Piecz pod przykryciem w 160°C około 2 godzin.", "Pod koniec posmaruj miodem i zrumień.", "Podawaj z kaszą."] },
  { id: 36, title: "Risotto z grzybami", category: "obiady", age: "dorosli", time: 40,
    ingredients: ["300 g ryżu arborio", "300 g grzybów", "1 l bulionu", "1 cebula", "100 ml białego wina", "parmezan", "masło"],
    steps: ["Podsmaż cebulę i grzyby.", "Dodaj ryż i wino, odparuj.", "Stopniowo dolewaj bulion, mieszając.", "Gotuj do miękkości ryżu.", "Dodaj masło i parmezan."] },
  { id: 37, title: "Filet z kurczaka w sosie śmietanowo-pieprzowym", category: "obiady", age: "dorosli", time: 35,
    ingredients: ["600 g piersi z kurczaka", "200 ml śmietany", "1 łyżka zielonego pieprzu", "bulion", "1 cebula", "sól", "ryż do podania"],
    steps: ["Kurczaka obsmaż i odłóż.", "Podsmaż cebulę, dodaj bulion.", "Wlej śmietanę i pieprz zielony.", "Włóż kurczaka i duś chwilę.", "Podawaj z ryżem."] },
  { id: 38, title: "Karkówka pieczona", category: "obiady", age: "dorosli", time: 90,
    ingredients: ["1 kg karkówki", "4 ząbki czosnku", "musztarda", "papryka słodka", "majeranek", "sól, pieprz", "oliwa"],
    steps: ["Mięso natrzyj marynatą z przypraw.", "Odstaw na kilka godzin.", "Zawiń w folię.", "Piecz w 180°C około 70 minut.", "Pod koniec odkryj, by się zrumieniło."] },
  { id: 39, title: "Zupa jarzynowa", category: "obiady", age: "seniorzy", time: 45,
    ingredients: ["2 marchewki", "1 pietruszka", "kawałek selera", "2 ziemniaki", "garść fasolki szparagowej", "groszek", "natka", "bulion warzywny"],
    steps: ["Warzywa pokrój w kostkę.", "Wrzuć do wrzącego bulionu.", "Gotuj do miękkości.", "Dopraw solą i pieprzem.", "Posyp natką pietruszki."] },
  { id: 40, title: "Kasza gryczana z gulaszem", category: "obiady", age: "seniorzy", time: 70,
    ingredients: ["300 g kaszy gryczanej", "500 g mięsa wieprzowego", "1 cebula", "bulion", "majeranek", "sól, pieprz", "mąka"],
    steps: ["Mięso pokrój i obsmaż z cebulą.", "Wlej bulion i duś do miękkości.", "Zagęść mąką.", "Ugotuj kaszę gryczaną.", "Podawaj kaszę polaną gulaszem."] },
  { id: 41, title: "Pulpety w sosie koperkowym", category: "obiady", age: "seniorzy", time: 45,
    ingredients: ["500 g mięsa mielonego", "1 jajko", "3 łyżki bułki tartej", "200 ml śmietany", "pęczek koperku", "bulion", "ziemniaki"],
    steps: ["Wymieszaj mięso z jajkiem i bułką, uformuj pulpety.", "Gotuj je w bulionie.", "Wlej zahartowaną śmietanę.", "Dodaj posiekany koperek.", "Podawaj z ziemniakami."] },
  { id: 42, title: "Ryba po grecku", category: "obiady", age: "seniorzy", time: 60,
    ingredients: ["500 g filetów rybnych", "3 marchewki", "1 pietruszka", "1 cebula", "koncentrat pomidorowy", "mąka", "sól, pieprz"],
    steps: ["Rybę usmaż w mące.", "Zetrzyj warzywa i poddusz.", "Dodaj koncentrat i dopraw.", "Ułóż rybę i przykryj warzywami.", "Schłodź i podawaj."] },
  { id: 43, title: "Krupnik", category: "obiady", age: "seniorzy", time: 60,
    ingredients: ["100 g kaszy jęczmiennej", "2 marchewki", "1 pietruszka", "2 ziemniaki", "bulion", "natka", "sól, pieprz"],
    steps: ["Ugotuj kaszę osobno.", "W bulionie gotuj pokrojone warzywa.", "Dodaj ugotowaną kaszę.", "Dopraw do smaku.", "Posyp natką."] },
  { id: 44, title: "Duszone warzywa z ziemniakami", category: "obiady", age: "seniorzy", time: 40,
    ingredients: ["1 cukinia", "1 papryka", "2 marchewki", "1 cebula", "passata", "800 g ziemniaków", "zioła prowansalskie"],
    steps: ["Podsmaż cebulę.", "Dodaj pokrojone warzywa.", "Wlej passatę i duś.", "Ugotuj ziemniaki.", "Podawaj warzywa z ziemniakami."] },
  { id: 45, title: "Filet z mintaja na parze", category: "obiady", age: "seniorzy", time: 30,
    ingredients: ["4 filety mintaja", "cytryna", "koperek", "sól", "ziemniaki", "marchewka"],
    steps: ["Filety dopraw i skrop cytryną.", "Gotuj na parze 12 minut.", "Ugotuj ziemniaki i marchewkę.", "Posyp rybę koperkiem.", "Podawaj z warzywami."] },
  { id: 46, title: "Kluski śląskie z sosem", category: "obiady", age: "seniorzy", time: 60,
    ingredients: ["1 kg ziemniaków", "mąka ziemniaczana", "1 jajko", "sól", "sos pieczeniowy", "mięso duszone"],
    steps: ["Ugotuj i przeciśnij ziemniaki.", "Dodaj mąkę i jajko, zagnieć ciasto.", "Formuj kluski z dziurką.", "Gotuj do wypłynięcia.", "Podawaj z sosem i mięsem."] },
  { id: 47, title: "Zupa krem z dyni", category: "obiady", age: "seniorzy", time: 45,
    ingredients: ["1 kg dyni", "1 cebula", "1 marchewka", "1 l bulionu", "100 ml śmietany", "imbir", "pestki dyni"],
    steps: ["Podsmaż cebulę.", "Dodaj pokrojoną dynię i marchewkę.", "Zalej bulionem i gotuj do miękkości.", "Zblenduj na krem, dodaj śmietanę.", "Posyp pestkami dyni."] },
  { id: 48, title: "Gotowany kurczak z ryżem i warzywami", category: "obiady", age: "seniorzy", time: 40,
    ingredients: ["500 g piersi z kurczaka", "300 g ryżu", "2 marchewki", "groszek", "bulion", "natka", "sól"],
    steps: ["Kurczaka ugotuj w bulionie.", "Ugotuj ryż.", "Marchewkę i groszek ugotuj na miękko.", "Pokrój kurczaka.", "Połącz wszystko i podawaj."] },
  { id: 49, title: "Leczo warzywne", category: "obiady", age: "seniorzy", time: 45,
    ingredients: ["3 papryki", "2 cukinie", "1 cebula", "400 g pomidorów", "kiełbasa (opcjonalnie)", "papryka słodka", "sól, pieprz"],
    steps: ["Podsmaż cebulę.", "Dodaj pokrojone papryki i cukinię.", "Dorzuć pomidory.", "Duś do miękkości warzyw.", "Dopraw i podawaj z pieczywem."] },
  { id: 50, title: "Barszcz czerwony z uszkami", category: "obiady", age: "seniorzy", time: 90,
    ingredients: ["1 kg buraków", "bulion warzywny", "majeranek", "czosnek", "ocet lub kwasek", "uszka z grzybami", "sól, pieprz"],
    steps: ["Buraki zetrzyj i ugotuj w bulionie.", "Przecedź wywar.", "Dopraw czosnkiem, majerankiem i kwaskiem.", "Ugotuj uszka osobno.", "Podawaj barszcz z uszkami."] },

  // ====================== SAŁATKI (50) ======================
  { id: 51, title: "Sałatka z kurczakiem i kukurydzą", category: "salatki", age: "dzieci", time: 20,
    ingredients: ["200 g piersi z kurczaka", "1 puszka kukurydzy", "1 ogórek", "garść sałaty", "3 łyżki jogurtu", "sól, pieprz"],
    steps: ["Kurczaka ugotuj lub usmaż i pokrój.", "Pokrój ogórek i sałatę.", "Wymieszaj z kukurydzą.", "Dodaj jogurt i dopraw.", "Wymieszaj i podawaj."] },
  { id: 52, title: "Sałatka jarzynowa", category: "salatki", age: "dzieci", time: 40,
    ingredients: ["3 marchewki", "1 pietruszka", "2 ziemniaki", "3 jajka", "1 puszka groszku", "ogórki kiszone", "majonez", "sól, pieprz"],
    steps: ["Ugotuj warzywa i jajka.", "Wszystko pokrój w kostkę.", "Dodaj groszek i ogórki.", "Wymieszaj z majonezem.", "Dopraw i schłodź."] },
  { id: 53, title: "Sałatka z makaronem i szynką", category: "salatki", age: "dzieci", time: 25,
    ingredients: ["200 g makaronu", "150 g szynki", "1 puszka kukurydzy", "1 papryka", "3 łyżki majonezu", "sól, pieprz"],
    steps: ["Ugotuj makaron i ostudź.", "Pokrój szynkę i paprykę.", "Wymieszaj z kukurydzą.", "Dodaj majonez.", "Dopraw i wymieszaj."] },
  { id: 54, title: "Sałatka owocowa", category: "salatki", age: "dzieci", time: 15,
    ingredients: ["1 banan", "1 jabłko", "1 pomarańcza", "garść winogron", "garść truskawek", "1 łyżka miodu", "sok z cytryny"],
    steps: ["Owoce umyj i pokrój.", "Wymieszaj w misce.", "Skrop sokiem z cytryny.", "Polej miodem.", "Podawaj schłodzoną."] },
  { id: 55, title: "Surówka z marchewki i jabłka", category: "salatki", age: "dzieci", time: 10,
    ingredients: ["3 marchewki", "1 jabłko", "1 łyżka soku z cytryny", "1 łyżka oleju", "szczypta cukru"],
    steps: ["Zetrzyj marchewkę i jabłko.", "Skrop sokiem z cytryny.", "Dodaj olej i cukier.", "Wymieszaj.", "Podawaj od razu."] },
  { id: 56, title: "Sałatka caprese", category: "salatki", age: "dzieci", time: 10,
    ingredients: ["3 pomidory", "250 g mozzarelli", "świeża bazylia", "oliwa", "sól, pieprz"],
    steps: ["Pokrój pomidory i mozzarellę w plastry.", "Ułóż na przemian na talerzu.", "Dodaj listki bazylii.", "Skrop oliwą.", "Dopraw solą i pieprzem."] },
  { id: 57, title: "Sałatka z ryżem i kukurydzą", category: "salatki", age: "dzieci", time: 25,
    ingredients: ["200 g ryżu", "1 puszka kukurydzy", "1 papryka", "1 ogórek", "3 łyżki jogurtu", "sól"],
    steps: ["Ugotuj ryż i ostudź.", "Pokrój paprykę i ogórek.", "Dodaj kukurydzę.", "Wymieszaj z jogurtem.", "Dopraw do smaku."] },
  { id: 58, title: "Surówka z białej kapusty", category: "salatki", age: "dzieci", time: 15,
    ingredients: ["1/2 główki kapusty białej", "1 marchewka", "1 łyżka oleju", "ocet, cukier", "sól"],
    steps: ["Poszatkuj kapustę i posól.", "Zetrzyj marchewkę.", "Wymieszaj składniki.", "Dodaj olej, ocet i cukier.", "Odstaw na chwilę przed podaniem."] },
  { id: 59, title: "Sałatka z serem i winogronami", category: "salatki", age: "dzieci", time: 15,
    ingredients: ["garść sałaty", "150 g sera żółtego", "garść winogron", "garść orzechów", "jogurt naturalny", "miód"],
    steps: ["Porwij sałatę.", "Pokrój ser i przekrój winogrona.", "Wymieszaj składniki.", "Dodaj orzechy.", "Polej jogurtem z miodem."] },
  { id: 60, title: "Mizeria", category: "salatki", age: "dzieci", time: 10,
    ingredients: ["2 ogórki", "200 ml śmietany", "koperek", "sól, pieprz", "szczypta cukru"],
    steps: ["Ogórki pokrój w plasterki i posól.", "Odsącz nadmiar wody.", "Dodaj śmietanę.", "Wmieszaj posiekany koperek.", "Dopraw i schłodź."] },
  { id: 61, title: "Sałatka z tuńczykiem i jajkiem", category: "salatki", age: "dzieci", time: 20,
    ingredients: ["1 puszka tuńczyka", "3 jajka", "1 puszka kukurydzy", "garść sałaty", "majonez", "sól, pieprz"],
    steps: ["Ugotuj jajka i pokrój.", "Odsącz tuńczyka.", "Wymieszaj z kukurydzą i sałatą.", "Dodaj majonez.", "Dopraw do smaku."] },
  { id: 62, title: "Surówka colesław", category: "salatki", age: "dzieci", time: 15,
    ingredients: ["1/2 kapusty białej", "2 marchewki", "majonez", "jogurt", "ocet jabłkowy", "sól, pieprz, cukier"],
    steps: ["Poszatkuj kapustę.", "Zetrzyj marchewkę.", "Wymieszaj majonez z jogurtem i octem.", "Połącz warzywa z sosem.", "Schłodź przed podaniem."] },
  { id: 63, title: "Sałatka z gruszką i serem", category: "salatki", age: "dzieci", time: 15,
    ingredients: ["garść rukoli", "1 gruszka", "100 g sera", "garść orzechów włoskich", "miód", "oliwa"],
    steps: ["Ułóż rukolę na talerzu.", "Dodaj pokrojoną gruszkę i ser.", "Posyp orzechami.", "Polej oliwą i miodem.", "Podawaj od razu."] },
  { id: 64, title: "Sałatka grecka", category: "salatki", age: "mlodzi", time: 15,
    ingredients: ["3 pomidory", "1 ogórek", "1 papryka", "1 cebula czerwona", "200 g fety", "oliwki", "oliwa, oregano"],
    steps: ["Pokrój warzywa w kostkę.", "Dodaj pokrojoną fetę i oliwki.", "Skrop oliwą.", "Posyp oregano.", "Delikatnie wymieszaj."] },
  { id: 65, title: "Sałatka cezar", category: "salatki", age: "mlodzi", time: 25,
    ingredients: ["sałata rzymska", "200 g kurczaka", "grzanki", "parmezan", "sos cezar", "boczek (opcjonalnie)"],
    steps: ["Usmaż kurczaka i pokrój.", "Porwij sałatę.", "Dodaj grzanki i kurczaka.", "Polej sosem cezar.", "Posyp parmezanem."] },
  { id: 66, title: "Sałatka z quinoa i awokado", category: "salatki", age: "mlodzi", time: 30,
    ingredients: ["150 g quinoa", "1 awokado", "garść pomidorków", "ogórek", "limonka", "oliwa", "kolendra"],
    steps: ["Ugotuj quinoa i ostudź.", "Pokrój awokado, pomidorki i ogórek.", "Wymieszaj z quinoa.", "Skrop limonką i oliwą.", "Posyp kolendrą."] },
  { id: 67, title: "Sałatka z grillowanym kurczakiem", category: "salatki", age: "mlodzi", time: 25,
    ingredients: ["200 g piersi z kurczaka", "mix sałat", "pomidorki", "ogórek", "sos winegret", "sól, pieprz"],
    steps: ["Kurczaka dopraw i zgrilluj.", "Przygotuj warzywa.", "Pokrój kurczaka w paski.", "Wymieszaj składniki.", "Polej winegretem."] },
  { id: 68, title: "Sałatka z burakiem i fetą", category: "salatki", age: "mlodzi", time: 20,
    ingredients: ["2 buraki pieczone", "150 g fety", "rukola", "orzechy włoskie", "oliwa", "ocet balsamiczny"],
    steps: ["Pokrój buraki w kostkę.", "Ułóż na rukoli.", "Dodaj pokruszoną fetę.", "Posyp orzechami.", "Polej oliwą i balsamico."] },
  { id: 69, title: "Tabbouleh", category: "salatki", age: "mlodzi", time: 25,
    ingredients: ["150 g kaszy bulgur", "pęczek natki", "mięta", "2 pomidory", "cytryna", "oliwa", "cebula"],
    steps: ["Ugotuj bulgur i ostudź.", "Posiekaj natkę, miętę i cebulę.", "Pokrój pomidory.", "Wymieszaj wszystko.", "Skrop cytryną i oliwą."] },
  { id: 70, title: "Sałatka z krewetkami", category: "salatki", age: "mlodzi", time: 25,
    ingredients: ["200 g krewetek", "mix sałat", "awokado", "pomidorki", "czosnek", "oliwa", "limonka"],
    steps: ["Krewetki podsmaż z czosnkiem.", "Przygotuj sałatę i warzywa.", "Dodaj awokado.", "Ułóż krewetki na wierzchu.", "Skrop limonką i oliwą."] },
  { id: 71, title: "Sałatka z soczewicą", category: "salatki", age: "mlodzi", time: 35,
    ingredients: ["200 g soczewicy", "1 papryka", "ogórek", "cebula czerwona", "natka", "oliwa", "cytryna"],
    steps: ["Ugotuj soczewicę i ostudź.", "Pokrój warzywa.", "Wymieszaj składniki.", "Skrop oliwą i cytryną.", "Posyp natką."] },
  { id: 72, title: "Poke bowl z łososiem", category: "salatki", age: "mlodzi", time: 30,
    ingredients: ["200 g świeżego łososia", "200 g ryżu", "awokado", "ogórek", "edamame", "sos sojowy", "sezam"],
    steps: ["Ugotuj ryż i ostudź.", "Pokrój łososia w kostkę.", "Pokrój warzywa.", "Ułóż wszystko w misce.", "Polej sosem sojowym, posyp sezamem."] },
  { id: 73, title: "Sałatka z rukolą i pomidorkami", category: "salatki", age: "mlodzi", time: 10,
    ingredients: ["garść rukoli", "garść pomidorków", "parmezan", "pestki słonecznika", "oliwa", "balsamico"],
    steps: ["Ułóż rukolę na talerzu.", "Dodaj przekrojone pomidorki.", "Posyp parmezanem i pestkami.", "Polej oliwą.", "Skrop octem balsamicznym."] },
  { id: 74, title: "Sałatka z halloumi", category: "salatki", age: "mlodzi", time: 20,
    ingredients: ["200 g sera halloumi", "mix sałat", "pomidorki", "ogórek", "miód", "oliwa", "cytryna"],
    steps: ["Halloumi pokrój i usmaż na patelni.", "Przygotuj sałatę i warzywa.", "Ułóż halloumi na wierzchu.", "Polej oliwą i cytryną.", "Skrop miodem."] },
  { id: 75, title: "Sałatka z kuskusem", category: "salatki", age: "mlodzi", time: 20,
    ingredients: ["150 g kuskusu", "1 papryka", "ogórek", "pomidor", "natka", "oliwa", "cytryna"],
    steps: ["Zalej kuskus wrzątkiem i odstaw.", "Pokrój warzywa.", "Wymieszaj z kuskusem.", "Skrop oliwą i cytryną.", "Posyp natką."] },
  { id: 76, title: "Sałatka tajska z wołowiną", category: "salatki", age: "mlodzi", time: 30,
    ingredients: ["300 g polędwicy wołowej", "mix sałat", "ogórek", "marchewka", "kolendra", "sos rybny", "limonka, chili"],
    steps: ["Wołowinę usmaż i pokrój w plastry.", "Pokrój warzywa w paski.", "Wymieszaj sos z limonki, sosu rybnego i chili.", "Połącz składniki.", "Polej sosem i posyp kolendrą."] },
  { id: 77, title: "Sałatka śledziowa", category: "salatki", age: "dorosli", time: 25,
    ingredients: ["300 g śledzi", "2 jabłka", "1 cebula", "ogórki kiszone", "majonez", "sól, pieprz"],
    steps: ["Pokrój śledzie w kawałki.", "Zetrzyj jabłka.", "Pokrój cebulę i ogórki.", "Wymieszaj z majonezem.", "Dopraw i schłodź."] },
  { id: 78, title: "Sałatka z wędzonym łososiem", category: "salatki", age: "dorosli", time: 20,
    ingredients: ["150 g wędzonego łososia", "mix sałat", "awokado", "ogórek", "kapary", "oliwa", "cytryna"],
    steps: ["Przygotuj sałatę i warzywa.", "Dodaj plastry łososia.", "Posyp kaparami.", "Polej oliwą i cytryną.", "Podawaj od razu."] },
  { id: 79, title: "Sałatka z pieczonym burakiem i orzechami", category: "salatki", age: "dorosli", time: 50,
    ingredients: ["3 buraki", "rukola", "ser kozi", "orzechy włoskie", "miód", "oliwa, balsamico"],
    steps: ["Buraki upiecz i pokrój.", "Ułóż na rukoli.", "Dodaj ser kozi i orzechy.", "Polej oliwą i balsamico.", "Skrop miodem."] },
  { id: 80, title: "Sałatka z fasolą i tuńczykiem", category: "salatki", age: "dorosli", time: 15,
    ingredients: ["1 puszka fasoli białej", "1 puszka tuńczyka", "1 cebula czerwona", "natka", "oliwa", "cytryna"],
    steps: ["Odsącz fasolę i tuńczyka.", "Pokrój cebulę.", "Wymieszaj składniki.", "Skrop oliwą i cytryną.", "Posyp natką."] },
  { id: 81, title: "Sałatka z brokułami i jajkiem", category: "salatki", age: "dorosli", time: 25,
    ingredients: ["1 brokuł", "3 jajka", "1 puszka kukurydzy", "jogurt naturalny", "majonez", "sól, pieprz"],
    steps: ["Brokuł ugotuj al dente i podziel na różyczki.", "Ugotuj jajka i pokrój.", "Dodaj kukurydzę.", "Wymieszaj jogurt z majonezem.", "Połącz wszystko i dopraw."] },
  { id: 82, title: "Sałatka grecka z oliwkami", category: "salatki", age: "dorosli", time: 15,
    ingredients: ["3 pomidory", "ogórek", "papryka", "cebula", "200 g fety", "oliwki czarne", "oliwa, oregano"],
    steps: ["Pokrój warzywa w dużą kostkę.", "Dodaj fetę i oliwki.", "Skrop oliwą.", "Posyp oregano.", "Wymieszaj delikatnie."] },
  { id: 83, title: "Sałatka z kaszą bulgur", category: "salatki", age: "dorosli", time: 25,
    ingredients: ["150 g kaszy bulgur", "ogórek", "pomidor", "natka", "mięta", "oliwa", "cytryna"],
    steps: ["Ugotuj bulgur i ostudź.", "Pokrój warzywa.", "Posiekaj zioła.", "Wymieszaj składniki.", "Skrop oliwą i cytryną."] },
  { id: 84, title: "Sałatka z kurczakiem curry", category: "salatki", age: "dorosli", time: 25,
    ingredients: ["200 g kurczaka", "jogurt naturalny", "1 łyżka curry", "winogrona", "seler naciowy", "orzechy", "sól"],
    steps: ["Kurczaka ugotuj i pokrój.", "Wymieszaj jogurt z curry.", "Dodaj winogrona i seler.", "Połącz z kurczakiem.", "Posyp orzechami."] },
  { id: 85, title: "Sałatka z serem pleśniowym i gruszką", category: "salatki", age: "dorosli", time: 15,
    ingredients: ["mix sałat", "1 gruszka", "100 g sera pleśniowego", "orzechy włoskie", "miód", "oliwa"],
    steps: ["Ułóż sałatę na talerzu.", "Dodaj pokrojoną gruszkę.", "Pokrusz ser pleśniowy.", "Posyp orzechami.", "Polej oliwą i miodem."] },
  { id: 86, title: "Sałatka z pieczarkami", category: "salatki", age: "dorosli", time: 20,
    ingredients: ["300 g pieczarek", "1 puszka kukurydzy", "1 papryka", "ser żółty", "majonez", "sól, pieprz"],
    steps: ["Pieczarki pokrój i podsmaż.", "Pokrój paprykę i ser.", "Dodaj kukurydzę.", "Wymieszaj z majonezem.", "Dopraw do smaku."] },
  { id: 87, title: "Sałatka z awokado i jajkiem", category: "salatki", age: "dorosli", time: 15,
    ingredients: ["2 awokado", "3 jajka", "pomidorki", "rukola", "oliwa", "cytryna, sól"],
    steps: ["Ugotuj jajka i pokrój.", "Pokrój awokado i pomidorki.", "Ułóż na rukoli.", "Skrop oliwą i cytryną.", "Dopraw solą."] },
  { id: 88, title: "Sałatka z papryki i fety", category: "salatki", age: "dorosli", time: 15,
    ingredients: ["3 papryki", "200 g fety", "oliwki", "cebula czerwona", "oliwa", "zioła"],
    steps: ["Pokrój papryki w paski.", "Dodaj pokrojoną fetę.", "Dorzuć oliwki i cebulę.", "Skrop oliwą.", "Posyp ziołami."] },
  { id: 89, title: "Sałatka jarzynowa tradycyjna", category: "salatki", age: "seniorzy", time: 50,
    ingredients: ["3 marchewki", "1 pietruszka", "kawałek selera", "3 ziemniaki", "3 jajka", "groszek", "ogórki kiszone", "majonez"],
    steps: ["Ugotuj warzywa i jajka.", "Pokrój wszystko drobno.", "Dodaj groszek i ogórki.", "Wymieszaj z majonezem.", "Dopraw i schłodź."] },
  { id: 90, title: "Sałatka z buraków", category: "salatki", age: "seniorzy", time: 60,
    ingredients: ["4 buraki", "1 cebula", "ocet", "olej", "sól, pieprz, cukier"],
    steps: ["Buraki ugotuj i obierz.", "Zetrzyj na tarce.", "Dodaj drobno pokrojoną cebulę.", "Dopraw octem, olejem i cukrem.", "Wymieszaj i schłodź."] },
  { id: 91, title: "Mizeria ze śmietaną", category: "salatki", age: "seniorzy", time: 10,
    ingredients: ["2 ogórki", "200 ml śmietany", "koperek", "sól, pieprz, cukier"],
    steps: ["Ogórki pokrój cienko i posól.", "Odsącz wodę.", "Dodaj śmietanę.", "Wmieszaj koperek.", "Dopraw szczyptą cukru."] },
  { id: 92, title: "Surówka z kiszonej kapusty", category: "salatki", age: "seniorzy", time: 10,
    ingredients: ["400 g kapusty kiszonej", "1 marchewka", "1 cebula", "olej", "cukier, pieprz"],
    steps: ["Kapustę odsącz i posiekaj.", "Zetrzyj marchewkę.", "Dodaj pokrojoną cebulę.", "Dopraw olejem i cukrem.", "Wymieszaj dokładnie."] },
  { id: 93, title: "Sałatka z selera i jabłka", category: "salatki", age: "seniorzy", time: 15,
    ingredients: ["1 seler", "2 jabłka", "garść rodzynek", "jogurt naturalny", "sok z cytryny", "sól"],
    steps: ["Zetrzyj seler i jabłka.", "Skrop sokiem z cytryny.", "Dodaj rodzynki.", "Wymieszaj z jogurtem.", "Dopraw solą."] },
  { id: 94, title: "Sałatka z marchewki gotowanej", category: "salatki", age: "seniorzy", time: 25,
    ingredients: ["4 marchewki", "1 puszka groszku", "jogurt naturalny", "natka", "sól, pieprz"],
    steps: ["Marchewkę ugotuj i pokrój w kostkę.", "Dodaj groszek.", "Wymieszaj z jogurtem.", "Dopraw solą i pieprzem.", "Posyp natką."] },
  { id: 95, title: "Sałatka ziemniaczana", category: "salatki", age: "seniorzy", time: 40,
    ingredients: ["600 g ziemniaków", "2 jajka", "ogórki kiszone", "1 cebula", "majonez", "szczypiorek"],
    steps: ["Ugotuj ziemniaki i jajka.", "Pokrój wszystko w kostkę.", "Dodaj ogórki i cebulę.", "Wymieszaj z majonezem.", "Posyp szczypiorkiem."] },
  { id: 96, title: "Surówka z pora", category: "salatki", age: "seniorzy", time: 15,
    ingredients: ["2 pory", "1 jabłko", "1 puszka kukurydzy", "majonez", "jogurt", "sól, pieprz"],
    steps: ["Pora pokrój w cienkie plasterki.", "Zetrzyj jabłko.", "Dodaj kukurydzę.", "Wymieszaj majonez z jogurtem.", "Połącz i dopraw."] },
  { id: 97, title: "Sałatka z jajek i szczypiorku", category: "salatki", age: "seniorzy", time: 20,
    ingredients: ["5 jajek", "pęczek szczypiorku", "majonez", "musztarda", "sól, pieprz"],
    steps: ["Ugotuj jajka na twardo.", "Pokrój w kostkę.", "Posiekaj szczypiorek.", "Wymieszaj majonez z musztardą.", "Połącz i dopraw."] },
  { id: 98, title: "Sałatka z fasolki szparagowej", category: "salatki", age: "seniorzy", time: 25,
    ingredients: ["400 g fasolki szparagowej", "pomidorki", "1 cebula", "oliwa", "ocet, sól"],
    steps: ["Fasolkę ugotuj al dente.", "Pokrój pomidorki i cebulę.", "Wymieszaj składniki.", "Skrop oliwą i octem.", "Dopraw solą."] },
  { id: 99, title: "Sałatka z dyni pieczonej", category: "salatki", age: "seniorzy", time: 40,
    ingredients: ["500 g dyni", "rukola", "ser feta", "pestki dyni", "oliwa", "miód"],
    steps: ["Dynię pokrój i upiecz.", "Ułóż na rukoli.", "Dodaj fetę i pestki.", "Polej oliwą.", "Skrop miodem."] },
  { id: 100, title: "Surówka z kapusty pekińskiej", category: "salatki", age: "seniorzy", time: 15,
    ingredients: ["1/2 kapusty pekińskiej", "1 papryka", "1 ogórek", "jogurt", "majonez", "sól, pieprz"],
    steps: ["Poszatkuj kapustę pekińską.", "Pokrój paprykę i ogórek.", "Wymieszaj jogurt z majonezem.", "Połącz składniki.", "Dopraw do smaku."] },

  // ====================== DESERY (50) ======================
  { id: 101, title: "Naleśniki z dżemem", category: "desery", age: "dzieci", time: 25,
    ingredients: ["200 g mąki", "2 jajka", "400 ml mleka", "szczypta soli", "dżem ulubiony", "cukier puder"],
    steps: ["Zmiksuj mąkę, jajka i mleko.", "Usmaż cienkie naleśniki.", "Posmaruj dżemem.", "Zwiń naleśniki.", "Posyp cukrem pudrem."] },
  { id: 102, title: "Galaretka owocowa", category: "desery", age: "dzieci", time: 20,
    ingredients: ["1 galaretka", "garść owoców", "500 ml wody"],
    steps: ["Rozpuść galaretkę we wrzątku.", "Ostudź lekko.", "Dodaj pokrojone owoce.", "Przelej do miseczek.", "Schłódź do stężenia."] },
  { id: 103, title: "Budyń waniliowy", category: "desery", age: "dzieci", time: 15,
    ingredients: ["1 budyń waniliowy", "500 ml mleka", "2 łyżki cukru"],
    steps: ["Wymieszaj budyń z odrobiną mleka.", "Resztę mleka zagotuj z cukrem.", "Wlej budyń i gotuj mieszając.", "Przelej do miseczek.", "Podawaj ciepły lub schłodzony."] },
  { id: 104, title: "Koktajl bananowo-truskawkowy", category: "desery", age: "dzieci", time: 10,
    ingredients: ["1 banan", "garść truskawek", "200 ml mleka", "1 łyżka miodu"],
    steps: ["Obierz banana.", "Umyj truskawki.", "Włóż wszystko do blendera.", "Dodaj mleko i miód.", "Zmiksuj na gładko."] },
  { id: 105, title: "Lody bananowe (nicecream)", category: "desery", age: "dzieci", time: 10,
    ingredients: ["3 mrożone banany", "2 łyżki kakao", "odrobina mleka"],
    steps: ["Pokrój i zamroź banany wcześniej.", "Włóż do blendera.", "Dodaj kakao i mleko.", "Zmiksuj na kremową masę.", "Podawaj od razu."] },
  { id: 106, title: "Ryż na mleku z jabłkami", category: "desery", age: "dzieci", time: 30,
    ingredients: ["150 g ryżu", "500 ml mleka", "2 jabłka", "cynamon", "cukier"],
    steps: ["Ugotuj ryż na mleku.", "Zetrzyj lub poddusz jabłka.", "Połącz z ryżem.", "Posyp cynamonem i cukrem.", "Podawaj ciepły."] },
  { id: 107, title: "Kisiel truskawkowy", category: "desery", age: "dzieci", time: 15,
    ingredients: ["1 kisiel truskawkowy", "500 ml wody", "garść truskawek"],
    steps: ["Rozprowadź kisiel w zimnej wodzie.", "Zagotuj resztę wody.", "Wlej kisiel mieszając.", "Dodaj truskawki.", "Podawaj ciepły lub zimny."] },
  { id: 108, title: "Bananowe muffinki", category: "desery", age: "dzieci", time: 35,
    ingredients: ["2 banany", "200 g mąki", "2 jajka", "80 g cukru", "100 ml oleju", "łyżeczka proszku do pieczenia"],
    steps: ["Rozgnieć banany.", "Wymieszaj z jajkami, cukrem i olejem.", "Dodaj mąkę z proszkiem.", "Rozłóż do foremek.", "Piecz 25 minut w 180°C."] },
  { id: 109, title: "Czekoladowe kuleczki mocy", category: "desery", age: "dzieci", time: 20,
    ingredients: ["150 g daktyli", "100 g płatków owsianych", "2 łyżki kakao", "2 łyżki masła orzechowego", "wiórki kokosowe"],
    steps: ["Zmiksuj daktyle z płatkami.", "Dodaj kakao i masło orzechowe.", "Formuj kuleczki.", "Obtocz w wiórkach.", "Schłódź w lodówce."] },
  { id: 110, title: "Owoce w czekoladzie", category: "desery", age: "dzieci", time: 20,
    ingredients: ["truskawki", "banany", "winogrona", "200 g czekolady", "posypka"],
    steps: ["Rozpuść czekoladę w kąpieli wodnej.", "Umyj i osusz owoce.", "Zanurzaj owoce w czekoladzie.", "Posyp posypką.", "Schłódź do zastygnięcia."] },
  { id: 111, title: "Pudding chia", category: "desery", age: "dzieci", time: 15,
    ingredients: ["3 łyżki nasion chia", "200 ml mleka", "1 łyżka miodu", "owoce"],
    steps: ["Wymieszaj chia z mlekiem i miodem.", "Odstaw na 10 minut i zamieszaj.", "Wstaw do lodówki na kilka godzin.", "Dodaj owoce.", "Podawaj schłodzony."] },
  { id: 112, title: "Gofry", category: "desery", age: "dzieci", time: 30,
    ingredients: ["250 g mąki", "2 jajka", "300 ml mleka", "80 g masła", "2 łyżki cukru", "proszek do pieczenia", "bita śmietana, owoce"],
    steps: ["Zmiksuj składniki na gładkie ciasto.", "Rozgrzej gofrownicę.", "Wlewaj porcje ciasta.", "Piecz na złoto.", "Podawaj z bitą śmietaną i owocami."] },
  { id: 113, title: "Racuchy z jabłkami", category: "desery", age: "dzieci", time: 30,
    ingredients: ["250 g mąki", "2 jajka", "200 ml kefiru", "2 jabłka", "cukier", "proszek do pieczenia", "olej"],
    steps: ["Wymieszaj mąkę, jajka i kefir.", "Dodaj starte jabłka.", "Smaż porcje na oleju.", "Rumień z obu stron.", "Posyp cukrem pudrem."] },
  { id: 114, title: "Tiramisu", category: "desery", age: "mlodzi", time: 40,
    ingredients: ["250 g mascarpone", "3 jajka", "80 g cukru", "biszkopty", "mocna kawa", "kakao", "amaretto (opcjonalnie)"],
    steps: ["Utrzyj żółtka z cukrem.", "Dodaj mascarpone.", "Wmieszaj ubitą pianę z białek.", "Maczaj biszkopty w kawie i układaj warstwami z kremem.", "Posyp kakao i schłódź."] },
  { id: 115, title: "Mus czekoladowy", category: "desery", age: "mlodzi", time: 25,
    ingredients: ["200 g czekolady", "3 jajka", "2 łyżki cukru", "200 ml śmietany kremówki"],
    steps: ["Rozpuść czekoladę.", "Dodaj żółtka.", "Ubij białka z cukrem.", "Ubij śmietanę.", "Połącz wszystko delikatnie i schłódź."] },
  { id: 116, title: "Panna cotta", category: "desery", age: "mlodzi", time: 30,
    ingredients: ["500 ml śmietany kremówki", "60 g cukru", "1 laska wanilii", "3 listki żelatyny", "owoce na sos"],
    steps: ["Podgrzej śmietanę z cukrem i wanilią.", "Dodaj namoczoną żelatynę.", "Przelej do foremek.", "Schłódź do stężenia.", "Podawaj z sosem owocowym."] },
  { id: 117, title: "Sernik na zimno", category: "desery", age: "mlodzi", time: 40,
    ingredients: ["500 g serka homogenizowanego", "200 ml śmietany kremówki", "100 g cukru", "biszkopty", "żelatyna", "owoce"],
    steps: ["Przygotuj spód z biszkoptów.", "Zmiksuj serek z cukrem.", "Dodaj rozpuszczoną żelatynę i ubitą śmietanę.", "Wyłóż na spód.", "Schłódź i udekoruj owocami."] },
  { id: 118, title: "Brownie", category: "desery", age: "mlodzi", time: 45,
    ingredients: ["200 g czekolady", "150 g masła", "200 g cukru", "3 jajka", "100 g mąki", "orzechy"],
    steps: ["Rozpuść czekoladę z masłem.", "Dodaj cukier i jajka.", "Wmieszaj mąkę i orzechy.", "Przelej do formy.", "Piecz 30 minut w 180°C."] },
  { id: 119, title: "Crème brûlée", category: "desery", age: "mlodzi", time: 60,
    ingredients: ["500 ml śmietany kremówki", "5 żółtek", "80 g cukru", "wanilia", "cukier do karmelizacji"],
    steps: ["Podgrzej śmietanę z wanilią.", "Utrzyj żółtka z cukrem.", "Połącz i przelej do kokilek.", "Piecz w kąpieli wodnej w 150°C.", "Schłódź i skarmelizuj cukier na wierzchu."] },
  { id: 120, title: "Sernik japoński", category: "desery", age: "mlodzi", time: 70,
    ingredients: ["250 g serka kremowego", "6 jajek", "100 g cukru", "60 g mąki", "50 g masła", "100 ml mleka"],
    steps: ["Połącz serek, masło i mleko.", "Dodaj żółtka i mąkę.", "Ubij białka z cukrem.", "Delikatnie połącz masy.", "Piecz w kąpieli wodnej 60 minut w 160°C."] },
  { id: 121, title: "Domowe trufle czekoladowe", category: "desery", age: "mlodzi", time: 30,
    ingredients: ["200 g czekolady", "100 ml śmietany kremówki", "20 g masła", "kakao do obtoczenia"],
    steps: ["Zagotuj śmietanę.", "Zalej nią czekoladę i wymieszaj.", "Dodaj masło i schłódź.", "Formuj kulki.", "Obtocz w kakao."] },
  { id: 122, title: "Mus z mango", category: "desery", age: "mlodzi", time: 20,
    ingredients: ["2 mango", "200 ml śmietany kremówki", "2 łyżki cukru pudru", "sok z limonki"],
    steps: ["Zblenduj mango.", "Ubij śmietanę z cukrem.", "Połącz z musem z mango.", "Skrop limonką.", "Schłódź przed podaniem."] },
  { id: 123, title: "Lody waniliowe", category: "desery", age: "mlodzi", time: 30,
    ingredients: ["500 ml śmietany kremówki", "200 ml mleka skondensowanego", "wanilia"],
    steps: ["Ubij śmietanę.", "Dodaj mleko skondensowane i wanilię.", "Delikatnie wymieszaj.", "Przelej do pojemnika.", "Zamroź na kilka godzin."] },
  { id: 124, title: "Pancakes amerykańskie z owocami", category: "desery", age: "mlodzi", time: 25,
    ingredients: ["200 g mąki", "1 jajko", "250 ml mleka", "2 łyżki cukru", "proszek do pieczenia", "owoce, syrop klonowy"],
    steps: ["Wymieszaj suche składniki.", "Dodaj jajko i mleko.", "Smaż grube placuszki na patelni.", "Układaj w stosik.", "Polej syropem i dodaj owoce."] },
  { id: 125, title: "Deser lodowy z owocami", category: "desery", age: "mlodzi", time: 10,
    ingredients: ["lody waniliowe", "owoce sezonowe", "polewa czekoladowa", "bita śmietana", "orzechy"],
    steps: ["Nałóż gałki lodów do pucharka.", "Dodaj owoce.", "Polej polewą czekoladową.", "Udekoruj bitą śmietaną.", "Posyp orzechami."] },
  { id: 126, title: "Tarta cytrynowa", category: "desery", age: "mlodzi", time: 70,
    ingredients: ["spód kruchy", "4 cytryny", "4 jajka", "150 g cukru", "100 g masła"],
    steps: ["Upiecz spód kruchy.", "Wymieszaj sok z cytryn, jajka i cukier.", "Podgrzewaj z masłem do zgęstnienia.", "Wlej na spód.", "Schłódź przed podaniem."] },
  { id: 127, title: "Szarlotka na ciepło z lodami", category: "desery", age: "dorosli", time: 70,
    ingredients: ["ciasto kruche", "1 kg jabłek", "cynamon", "cukier", "lody waniliowe"],
    steps: ["Jabłka poddusz z cynamonem i cukrem.", "Wyłóż formę ciastem.", "Nałóż jabłka i przykryj ciastem.", "Piecz 40 minut w 180°C.", "Podawaj ciepłą z lodami."] },
  { id: 128, title: "Krem kawowy", category: "desery", age: "dorosli", time: 20,
    ingredients: ["250 g mascarpone", "200 ml śmietany kremówki", "mocna kawa", "cukier puder", "kakao"],
    steps: ["Ubij śmietanę z cukrem.", "Dodaj mascarpone.", "Wmieszaj wystudzoną kawę.", "Przełóż do pucharków.", "Posyp kakao i schłódź."] },
  { id: 129, title: "Deser z mascarpone i owocami", category: "desery", age: "dorosli", time: 20,
    ingredients: ["250 g mascarpone", "jogurt grecki", "owoce", "miód", "granola"],
    steps: ["Wymieszaj mascarpone z jogurtem.", "Dodaj miód.", "Przełóż do pucharków.", "Dodaj owoce.", "Posyp granolą."] },
  { id: 130, title: "Kompot z suszu", category: "desery", age: "dorosli", time: 60,
    ingredients: ["300 g owoców suszonych", "1,5 l wody", "cukier", "goździki", "cynamon"],
    steps: ["Owoce zalej wodą.", "Dodaj przyprawy.", "Gotuj na małym ogniu około 40 minut.", "Dosłódź do smaku.", "Podawaj ciepły lub zimny."] },
  { id: 131, title: "Pieczone jabłka z cynamonem", category: "desery", age: "dorosli", time: 40,
    ingredients: ["4 jabłka", "orzechy", "rodzynki", "miód", "cynamon", "masło"],
    steps: ["Wydrąż gniazda jabłek.", "Wypełnij orzechami i rodzynkami.", "Polej miodem i posyp cynamonem.", "Dodaj odrobinę masła.", "Piecz 30 minut w 180°C."] },
  { id: 132, title: "Galaretka z owocami i bitą śmietaną", category: "desery", age: "dorosli", time: 30,
    ingredients: ["2 galaretki", "owoce", "200 ml śmietany kremówki", "cukier puder"],
    steps: ["Przygotuj galaretkę i dodaj owoce.", "Schłódź do stężenia.", "Ubij śmietanę z cukrem.", "Nałóż śmietanę na galaretkę.", "Podawaj schłodzoną."] },
  { id: 133, title: "Krem z kaszy jaglanej", category: "desery", age: "dorosli", time: 30,
    ingredients: ["100 g kaszy jaglanej", "300 ml mleka", "1 banan", "2 łyżki kakao", "miód"],
    steps: ["Ugotuj kaszę na mleku.", "Dodaj banana i kakao.", "Zblenduj na gładko.", "Dosłódź miodem.", "Schłódź przed podaniem."] },
  { id: 134, title: "Suflet czekoladowy", category: "desery", age: "dorosli", time: 30,
    ingredients: ["100 g czekolady", "50 g masła", "2 jajka", "2 łyżki cukru", "1 łyżka mąki"],
    steps: ["Rozpuść czekoladę z masłem.", "Dodaj żółtka, cukier i mąkę.", "Wmieszaj ubite białka.", "Przelej do kokilek.", "Piecz 12 minut w 200°C, podawaj od razu."] },
  { id: 135, title: "Mus jabłkowy", category: "desery", age: "dorosli", time: 30,
    ingredients: ["6 jabłek", "cynamon", "cukier", "sok z cytryny"],
    steps: ["Jabłka obierz i pokrój.", "Duś z odrobiną wody.", "Dodaj cynamon i cukier.", "Zblenduj na mus.", "Schłódź przed podaniem."] },
  { id: 136, title: "Deser jogurtowy z granolą", category: "desery", age: "dorosli", time: 10,
    ingredients: ["400 g jogurtu greckiego", "granola", "owoce", "miód", "orzechy"],
    steps: ["Nałóż warstwę jogurtu.", "Dodaj granolę.", "Dołóż owoce.", "Polej miodem.", "Posyp orzechami."] },
  { id: 137, title: "Budyń czekoladowy domowy", category: "desery", age: "dorosli", time: 20,
    ingredients: ["500 ml mleka", "3 łyżki kakao", "3 łyżki cukru", "2 łyżki mąki ziemniaczanej"],
    steps: ["Wymieszaj kakao, cukier i mąkę z odrobiną mleka.", "Resztę mleka zagotuj.", "Wlej masę, mieszając do zgęstnienia.", "Przelej do miseczek.", "Schłódź przed podaniem."] },
  { id: 138, title: "Kasza manna z owocami", category: "desery", age: "dorosli", time: 20,
    ingredients: ["4 łyżki kaszy manny", "500 ml mleka", "cukier", "owoce", "cynamon"],
    steps: ["Zagotuj mleko z cukrem.", "Wsyp kaszę mannę mieszając.", "Gotuj do zgęstnienia.", "Przełóż do miseczek.", "Dodaj owoce i cynamon."] },
  { id: 139, title: "Kisiel z owocami", category: "desery", age: "seniorzy", time: 20,
    ingredients: ["2 łyżki mąki ziemniaczanej", "500 ml soku owocowego", "cukier", "owoce"],
    steps: ["Rozprowadź mąkę w zimnym soku.", "Resztę soku zagotuj.", "Wlej mieszankę i gotuj.", "Dodaj owoce.", "Podawaj ciepły lub zimny."] },
  { id: 140, title: "Budyń waniliowy domowy", category: "desery", age: "seniorzy", time: 20,
    ingredients: ["500 ml mleka", "3 żółtka", "3 łyżki cukru", "2 łyżki mąki ziemniaczanej", "wanilia"],
    steps: ["Utrzyj żółtka z cukrem i mąką.", "Zagotuj mleko z wanilią.", "Wlej masę mieszając.", "Gotuj do zgęstnienia.", "Przelej do miseczek i schłódź."] },
  { id: 141, title: "Galaretka mleczna", category: "desery", age: "seniorzy", time: 25,
    ingredients: ["500 ml mleka", "żelatyna", "3 łyżki cukru", "wanilia"],
    steps: ["Podgrzej mleko z cukrem i wanilią.", "Dodaj namoczoną żelatynę.", "Wymieszaj do rozpuszczenia.", "Przelej do foremek.", "Schłódź do stężenia."] },
  { id: 142, title: "Kompot owocowy", category: "desery", age: "seniorzy", time: 30,
    ingredients: ["500 g owoców", "1,5 l wody", "cukier"],
    steps: ["Owoce umyj i pokrój.", "Zalej wodą.", "Dodaj cukier.", "Gotuj 20 minut.", "Ostudź przed podaniem."] },
  { id: 143, title: "Pieczone jabłko", category: "desery", age: "seniorzy", time: 35,
    ingredients: ["4 jabłka", "miód", "cynamon", "rodzynki"],
    steps: ["Wydrąż jabłka.", "Wypełnij rodzynkami.", "Polej miodem i posyp cynamonem.", "Piecz 25 minut w 180°C.", "Podawaj ciepłe."] },
  { id: 144, title: "Ryż zapiekany z jabłkami", category: "desery", age: "seniorzy", time: 45,
    ingredients: ["150 g ryżu", "500 ml mleka", "3 jabłka", "2 jajka", "cukier, cynamon"],
    steps: ["Ugotuj ryż na mleku.", "Dodaj żółtka i cukier.", "Wmieszaj starte jabłka.", "Dodaj ubite białka.", "Zapiekaj 25 minut w 180°C."] },
  { id: 145, title: "Mus owocowy", category: "desery", age: "seniorzy", time: 15,
    ingredients: ["300 g owoców", "jogurt naturalny", "miód"],
    steps: ["Zblenduj owoce.", "Dodaj jogurt.", "Dosłódź miodem.", "Przełóż do pucharków.", "Schłódź przed podaniem."] },
  { id: 146, title: "Kasza jaglana z musem owocowym", category: "desery", age: "seniorzy", time: 30,
    ingredients: ["100 g kaszy jaglanej", "400 ml mleka", "owoce", "miód"],
    steps: ["Ugotuj kaszę na mleku.", "Zblenduj na gładko.", "Przygotuj mus z owoców.", "Połącz warstwami.", "Polej miodem."] },
  { id: 147, title: "Twarożek z owocami", category: "desery", age: "seniorzy", time: 10,
    ingredients: ["250 g twarogu", "jogurt naturalny", "owoce", "miód"],
    steps: ["Rozetrzyj twaróg z jogurtem.", "Dodaj miód.", "Pokrój owoce.", "Połącz wszystko.", "Podawaj schłodzony."] },
  { id: 148, title: "Deser z biszkoptów i kremu", category: "desery", age: "seniorzy", time: 30,
    ingredients: ["biszkopty", "budyń waniliowy", "owoce", "mleko"],
    steps: ["Ugotuj budyń.", "Ułóż warstwę biszkoptów.", "Nałóż budyń.", "Powtórz warstwy.", "Udekoruj owocami i schłódź."] },
  { id: 149, title: "Jogurt z miodem i orzechami", category: "desery", age: "seniorzy", time: 5,
    ingredients: ["400 g jogurtu greckiego", "miód", "orzechy włoskie", "cynamon"],
    steps: ["Przełóż jogurt do miseczek.", "Polej miodem.", "Posyp orzechami.", "Dodaj szczyptę cynamonu.", "Podawaj od razu."] },
  { id: 150, title: "Galaretka z brzoskwiniami", category: "desery", age: "seniorzy", time: 25,
    ingredients: ["1 galaretka", "1 puszka brzoskwiń", "500 ml wody"],
    steps: ["Rozpuść galaretkę we wrzątku.", "Ostudź lekko.", "Dodaj pokrojone brzoskwinie.", "Przelej do miseczek.", "Schłódź do stężenia."] },

  // ====================== CIASTA (50) ======================
  { id: 151, title: "Babeczki czekoladowe", category: "ciasta", age: "dzieci", time: 35,
    ingredients: ["200 g mąki", "100 g cukru", "2 łyżki kakao", "2 jajka", "100 ml oleju", "100 ml mleka", "proszek do pieczenia"],
    steps: ["Wymieszaj suche składniki.", "Dodaj jajka, olej i mleko.", "Rozłóż do foremek.", "Piecz 20 minut w 180°C.", "Ostudź przed podaniem."] },
  { id: 152, title: "Ciasto marchewkowe", category: "ciasta", age: "dzieci", time: 60,
    ingredients: ["3 marchewki", "250 g mąki", "150 g cukru", "3 jajka", "150 ml oleju", "cynamon", "proszek do pieczenia"],
    steps: ["Zetrzyj marchewki.", "Ubij jajka z cukrem.", "Dodaj olej i marchewkę.", "Wmieszaj mąkę z przyprawami.", "Piecz 45 minut w 175°C."] },
  { id: 153, title: "Muffinki jagodowe", category: "ciasta", age: "dzieci", time: 35,
    ingredients: ["250 g mąki", "100 g cukru", "1 jajko", "200 ml mleka", "80 ml oleju", "garść jagód", "proszek do pieczenia"],
    steps: ["Wymieszaj suche składniki.", "Dodaj jajko, mleko i olej.", "Wmieszaj jagody.", "Rozłóż do foremek.", "Piecz 25 minut w 180°C."] },
  { id: 154, title: "Murzynek", category: "ciasta", age: "dzieci", time: 60,
    ingredients: ["300 g mąki", "200 g cukru", "4 jajka", "200 g masła", "4 łyżki kakao", "200 ml mleka", "proszek do pieczenia"],
    steps: ["Roztop masło z kakao, cukrem i mlekiem.", "Ostudź i dodaj jajka.", "Wmieszaj mąkę z proszkiem.", "Przelej do formy.", "Piecz 40 minut w 180°C."] },
  { id: 155, title: "Biszkopt z owocami", category: "ciasta", age: "dzieci", time: 45,
    ingredients: ["5 jajek", "150 g cukru", "150 g mąki", "owoce", "cukier puder"],
    steps: ["Ubij jajka z cukrem na puszysto.", "Delikatnie wmieszaj mąkę.", "Przelej do formy.", "Piecz 30 minut w 170°C.", "Udekoruj owocami i cukrem pudrem."] },
  { id: 156, title: "Ciastka owsiane", category: "ciasta", age: "dzieci", time: 30,
    ingredients: ["200 g płatków owsianych", "1 banan", "100 g mąki", "80 g cukru", "80 g masła", "rodzynki"],
    steps: ["Rozgnieć banana.", "Wymieszaj z masłem i cukrem.", "Dodaj płatki, mąkę i rodzynki.", "Formuj ciastka na blasze.", "Piecz 15 minut w 180°C."] },
  { id: 157, title: "Ciasteczka maślane", category: "ciasta", age: "dzieci", time: 40,
    ingredients: ["250 g mąki", "150 g masła", "100 g cukru pudru", "1 jajko", "wanilia"],
    steps: ["Zagnieć ciasto z wszystkich składników.", "Schłódź w lodówce.", "Rozwałkuj i wycinaj kształty.", "Ułóż na blasze.", "Piecz 12 minut w 180°C."] },
  { id: 158, title: "Ciasto bananowe", category: "ciasta", age: "dzieci", time: 60,
    ingredients: ["3 banany", "250 g mąki", "150 g cukru", "2 jajka", "100 ml oleju", "proszek do pieczenia"],
    steps: ["Rozgnieć banany.", "Wymieszaj z jajkami, cukrem i olejem.", "Dodaj mąkę z proszkiem.", "Przelej do formy.", "Piecz 45 minut w 175°C."] },
  { id: 159, title: "Pierniczki", category: "ciasta", age: "dzieci", time: 50,
    ingredients: ["400 g mąki", "150 g miodu", "100 g cukru", "1 jajko", "przyprawa korzenna", "soda"],
    steps: ["Podgrzej miód z cukrem.", "Wymieszaj z mąką, jajkiem i przyprawami.", "Zagnieć ciasto i schłódź.", "Wykrawaj kształty.", "Piecz 10 minut w 180°C."] },
  { id: 160, title: "Rogaliki z dżemem", category: "ciasta", age: "dzieci", time: 50,
    ingredients: ["300 g mąki", "200 g masła", "200 g twarogu", "dżem", "cukier puder"],
    steps: ["Zagnieć ciasto z mąki, masła i twarogu.", "Schłódź.", "Rozwałkuj i pokrój na trójkąty.", "Nałóż dżem i zwiń rogaliki.", "Piecz 20 minut w 180°C."] },
  { id: 161, title: "Ciasto jogurtowe", category: "ciasta", age: "dzieci", time: 55,
    ingredients: ["200 g jogurtu", "250 g mąki", "150 g cukru", "3 jajka", "100 ml oleju", "proszek do pieczenia"],
    steps: ["Ubij jajka z cukrem.", "Dodaj jogurt i olej.", "Wmieszaj mąkę z proszkiem.", "Przelej do formy.", "Piecz 40 minut w 175°C."] },
  { id: 162, title: "Brownie dla dzieci", category: "ciasta", age: "dzieci", time: 40,
    ingredients: ["150 g czekolady", "100 g masła", "150 g cukru", "2 jajka", "80 g mąki"],
    steps: ["Rozpuść czekoladę z masłem.", "Dodaj cukier i jajka.", "Wmieszaj mąkę.", "Przelej do formy.", "Piecz 25 minut w 180°C."] },
  { id: 163, title: "Babka piaskowa", category: "ciasta", age: "dzieci", time: 60,
    ingredients: ["250 g masła", "200 g cukru", "4 jajka", "300 g mąki", "100 g mąki ziemniaczanej", "proszek do pieczenia"],
    steps: ["Utrzyj masło z cukrem.", "Dodawaj jajka po jednym.", "Wmieszaj mąki z proszkiem.", "Przelej do formy.", "Piecz 50 minut w 170°C."] },
  { id: 164, title: "Sernik klasyczny", category: "ciasta", age: "mlodzi", time: 90,
    ingredients: ["1 kg sera mielonego", "200 g cukru", "5 jajek", "100 g masła", "budyń waniliowy", "rodzynki"],
    steps: ["Utrzyj masło z cukrem.", "Dodawaj jajka i ser.", "Wmieszaj budyń.", "Przelej do formy.", "Piecz 60 minut w 170°C."] },
  { id: 165, title: "Tarta z owocami", category: "ciasta", age: "mlodzi", time: 70,
    ingredients: ["spód kruchy", "budyń lub krem", "owoce sezonowe", "galaretka do polania"],
    steps: ["Upiecz spód kruchy.", "Nałóż krem.", "Ułóż owoce.", "Zalej galaretką.", "Schłódź przed podaniem."] },
  { id: 166, title: "Ciasto czekoladowe z malinami", category: "ciasta", age: "mlodzi", time: 60,
    ingredients: ["200 g czekolady", "150 g masła", "200 g cukru", "4 jajka", "150 g mąki", "maliny"],
    steps: ["Rozpuść czekoladę z masłem.", "Dodaj cukier i jajka.", "Wmieszaj mąkę.", "Dodaj maliny i przelej do formy.", "Piecz 35 minut w 180°C."] },
  { id: 167, title: "Red velvet", category: "ciasta", age: "mlodzi", time: 80,
    ingredients: ["300 g mąki", "200 g cukru", "2 jajka", "barwnik czerwony", "kakao", "maślanka", "serek do kremu"],
    steps: ["Połącz mokre składniki z barwnikiem.", "Dodaj suche składniki.", "Upiecz blaty.", "Przygotuj krem serowy.", "Przełóż blaty kremem."] },
  { id: 168, title: "Ciasto cytrynowe", category: "ciasta", age: "mlodzi", time: 60,
    ingredients: ["250 g mąki", "200 g cukru", "3 jajka", "150 g masła", "2 cytryny", "proszek do pieczenia"],
    steps: ["Utrzyj masło z cukrem.", "Dodaj jajka i sok z cytryny.", "Wmieszaj mąkę z proszkiem.", "Przelej do formy.", "Piecz 40 minut, polej lukrem cytrynowym."] },
  { id: 169, title: "Tarta czekoladowa", category: "ciasta", age: "mlodzi", time: 60,
    ingredients: ["spód kruchy", "200 g czekolady", "200 ml śmietany kremówki", "masło"],
    steps: ["Upiecz spód kruchy.", "Zagotuj śmietanę.", "Zalej czekoladę i wymieszaj.", "Wlej na spód.", "Schłódź do stężenia."] },
  { id: 170, title: "Cheesecake nowojorski", category: "ciasta", age: "mlodzi", time: 90,
    ingredients: ["600 g serka philadelphia", "150 g cukru", "3 jajka", "200 ml śmietany", "herbatniki", "masło"],
    steps: ["Przygotuj spód z herbatników i masła.", "Zmiksuj serek z cukrem.", "Dodaj jajka i śmietanę.", "Wlej na spód.", "Piecz 60 minut w 160°C i studź powoli."] },
  { id: 171, title: "Ciasto kawowe", category: "ciasta", age: "mlodzi", time: 70,
    ingredients: ["250 g mąki", "200 g cukru", "3 jajka", "150 g masła", "mocna kawa", "krem maślany"],
    steps: ["Utrzyj masło z cukrem.", "Dodaj jajka i kawę.", "Wmieszaj mąkę.", "Upiecz blat.", "Przełóż kremem kawowym."] },
  { id: 172, title: "Brownie z orzechami", category: "ciasta", age: "mlodzi", time: 45,
    ingredients: ["200 g czekolady", "150 g masła", "200 g cukru", "3 jajka", "100 g mąki", "150 g orzechów"],
    steps: ["Rozpuść czekoladę z masłem.", "Dodaj cukier i jajka.", "Wmieszaj mąkę i orzechy.", "Przelej do formy.", "Piecz 30 minut w 180°C."] },
  { id: 173, title: "Ciasto z kremem mascarpone", category: "ciasta", age: "mlodzi", time: 70,
    ingredients: ["biszkopt", "250 g mascarpone", "200 ml śmietany kremówki", "cukier puder", "owoce"],
    steps: ["Upiecz biszkopt.", "Ubij śmietanę z cukrem i mascarpone.", "Przekrój biszkopt.", "Przełóż kremem i owocami.", "Schłódź przed podaniem."] },
  { id: 174, title: "Muffinki czekoladowe", category: "ciasta", age: "mlodzi", time: 35,
    ingredients: ["250 g mąki", "100 g cukru", "3 łyżki kakao", "1 jajko", "200 ml mleka", "80 ml oleju", "kawałki czekolady"],
    steps: ["Wymieszaj suche składniki.", "Dodaj jajko, mleko i olej.", "Wmieszaj kawałki czekolady.", "Rozłóż do foremek.", "Piecz 25 minut w 180°C."] },
  { id: 175, title: "Beza", category: "ciasta", age: "mlodzi", time: 120,
    ingredients: ["4 białka", "200 g cukru", "1 łyżka mąki ziemniaczanej", "ocet", "bita śmietana", "owoce"],
    steps: ["Ubij białka na sztywno.", "Stopniowo dodawaj cukier.", "Dodaj mąkę i ocet.", "Piecz 90 minut w 130°C.", "Udekoruj śmietaną i owocami."] },
  { id: 176, title: "Tort naleśnikowy", category: "ciasta", age: "mlodzi", time: 60,
    ingredients: ["naleśniki", "250 g mascarpone", "śmietana kremówka", "owoce", "cukier puder"],
    steps: ["Usmaż naleśniki.", "Przygotuj krem z mascarpone.", "Przekładaj naleśniki kremem.", "Dodawaj owoce między warstwy.", "Schłódź przed podaniem."] },
  { id: 177, title: "Szarlotka", category: "ciasta", age: "dorosli", time: 80,
    ingredients: ["400 g mąki", "200 g masła", "100 g cukru", "2 jajka", "1,5 kg jabłek", "cynamon", "proszek do pieczenia"],
    steps: ["Zagnieć kruche ciasto.", "Jabłka zetrzyj i poddusz z cynamonem.", "Wyłóż formę ciastem.", "Nałóż jabłka i przykryj ciastem.", "Piecz 50 minut w 180°C."] },
  { id: 178, title: "Sernik tradycyjny", category: "ciasta", age: "dorosli", time: 90,
    ingredients: ["1 kg twarogu", "200 g cukru", "5 jajek", "150 g masła", "budyń", "skórka cytrynowa"],
    steps: ["Zmiel twaróg.", "Utrzyj masło z cukrem i żółtkami.", "Dodaj twaróg i budyń.", "Wmieszaj ubitą pianę.", "Piecz 70 minut w 160°C."] },
  { id: 179, title: "Makowiec", category: "ciasta", age: "dorosli", time: 120,
    ingredients: ["ciasto drożdżowe", "500 g masy makowej", "bakalie", "lukier"],
    steps: ["Przygotuj ciasto drożdżowe.", "Rozwałkuj i nałóż masę makową.", "Zwiń roladę.", "Piecz 50 minut w 180°C.", "Polej lukrem po ostudzeniu."] },
  { id: 180, title: "Piernik staropolski", category: "ciasta", age: "dorosli", time: 90,
    ingredients: ["500 g mąki", "300 g miodu", "150 g cukru", "2 jajka", "przyprawa korzenna", "soda", "powidła"],
    steps: ["Podgrzej miód z cukrem.", "Wymieszaj z mąką, jajkami i przyprawami.", "Odstaw ciasto.", "Upiecz blaty.", "Przełóż powidłami."] },
  { id: 181, title: "Ciasto orzechowe", category: "ciasta", age: "dorosli", time: 70,
    ingredients: ["200 g orzechów mielonych", "150 g cukru", "5 jajek", "100 g mąki", "krem maślany"],
    steps: ["Ubij jajka z cukrem.", "Wmieszaj orzechy i mąkę.", "Upiecz blat.", "Przygotuj krem.", "Przełóż blaty kremem."] },
  { id: 182, title: "Keks bakaliowy", category: "ciasta", age: "dorosli", time: 80,
    ingredients: ["300 g mąki", "200 g cukru", "200 g masła", "4 jajka", "bakalie", "proszek do pieczenia"],
    steps: ["Utrzyj masło z cukrem.", "Dodaj jajka.", "Wmieszaj mąkę i bakalie.", "Przelej do formy.", "Piecz 60 minut w 170°C."] },
  { id: 183, title: "Babka drożdżowa", category: "ciasta", age: "dorosli", time: 120,
    ingredients: ["500 g mąki", "200 ml mleka", "50 g drożdży", "100 g cukru", "3 jajka", "100 g masła", "rodzynki"],
    steps: ["Przygotuj rozczyn z drożdży.", "Zagnieć ciasto i odstaw do wyrośnięcia.", "Dodaj rodzynki.", "Przełóż do formy i ponownie odstaw.", "Piecz 45 minut w 180°C."] },
  { id: 184, title: "Jabłecznik kruchy", category: "ciasta", age: "dorosli", time: 80,
    ingredients: ["400 g mąki", "200 g masła", "100 g cukru", "2 jajka", "1 kg jabłek", "cynamon"],
    steps: ["Zagnieć kruche ciasto.", "Jabłka zetrzyj i poddusz.", "Wyłóż formę ciastem.", "Nałóż jabłka i kruszonkę.", "Piecz 50 minut w 180°C."] },
  { id: 185, title: "Sernik na zimno z owocami", category: "ciasta", age: "dorosli", time: 50,
    ingredients: ["500 g serka", "200 ml śmietany kremówki", "cukier", "żelatyna", "herbatniki", "owoce"],
    steps: ["Przygotuj spód z herbatników.", "Zmiksuj serek z cukrem.", "Dodaj żelatynę i ubitą śmietanę.", "Wyłóż na spód.", "Schłódź i udekoruj owocami."] },
  { id: 186, title: "Ciasto śliwkowe", category: "ciasta", age: "dorosli", time: 70,
    ingredients: ["250 g mąki", "150 g cukru", "150 g masła", "3 jajka", "500 g śliwek", "proszek do pieczenia"],
    steps: ["Utrzyj masło z cukrem.", "Dodaj jajka.", "Wmieszaj mąkę z proszkiem.", "Wyłóż ciasto i ułóż śliwki.", "Piecz 45 minut w 180°C."] },
  { id: 187, title: "Karpatka", category: "ciasta", age: "dorosli", time: 90,
    ingredients: ["ciasto parzone", "budyń", "250 g masła", "cukier puder"],
    steps: ["Upiecz dwa blaty z ciasta parzonego.", "Ugotuj budyń i ostudź.", "Utrzyj masło i połącz z budyniem.", "Przełóż blaty kremem.", "Posyp cukrem pudrem."] },
  { id: 188, title: "Wuzetka", category: "ciasta", age: "dorosli", time: 80,
    ingredients: ["biszkopt kakaowy", "śmietana kremówka", "powidła", "polewa czekoladowa"],
    steps: ["Upiecz biszkopt kakaowy.", "Przekrój na blaty.", "Przełóż powidłami i bitą śmietaną.", "Polej polewą czekoladową.", "Schłódź przed podaniem."] },
  { id: 189, title: "Babka piaskowa tradycyjna", category: "ciasta", age: "seniorzy", time: 70,
    ingredients: ["250 g masła", "200 g cukru", "5 jajek", "300 g mąki", "100 g mąki ziemniaczanej", "proszek do pieczenia"],
    steps: ["Utrzyj masło z cukrem.", "Dodawaj jajka.", "Wmieszaj mąki z proszkiem.", "Przelej do formy.", "Piecz 55 minut w 170°C."] },
  { id: 190, title: "Ciasto ucierane z owocami", category: "ciasta", age: "seniorzy", time: 70,
    ingredients: ["250 g mąki", "150 g cukru", "150 g masła", "3 jajka", "owoce sezonowe", "proszek do pieczenia"],
    steps: ["Utrzyj masło z cukrem.", "Dodaj jajka.", "Wmieszaj mąkę z proszkiem.", "Wyłóż ciasto i ułóż owoce.", "Piecz 45 minut w 175°C."] },
  { id: 191, title: "Drożdżówka z kruszonką", category: "ciasta", age: "seniorzy", time: 100,
    ingredients: ["500 g mąki", "200 ml mleka", "40 g drożdży", "80 g cukru", "2 jajka", "masło", "kruszonka"],
    steps: ["Przygotuj rozczyn drożdżowy.", "Zagnieć ciasto i odstaw.", "Rozłóż na blasze.", "Posyp kruszonką.", "Piecz 30 minut w 180°C."] },
  { id: 192, title: "Placek z rabarbarem", category: "ciasta", age: "seniorzy", time: 70,
    ingredients: ["250 g mąki", "150 g cukru", "150 g masła", "3 jajka", "400 g rabarbaru", "proszek do pieczenia"],
    steps: ["Utrzyj masło z cukrem.", "Dodaj jajka.", "Wmieszaj mąkę z proszkiem.", "Wyłóż ciasto i ułóż rabarbar.", "Piecz 45 minut w 180°C."] },
  { id: 193, title: "Ciasto marchewkowe lekkie", category: "ciasta", age: "seniorzy", time: 60,
    ingredients: ["2 marchewki", "200 g mąki", "100 g cukru", "2 jajka", "100 ml oleju", "cynamon", "proszek do pieczenia"],
    steps: ["Zetrzyj marchewki.", "Ubij jajka z cukrem.", "Dodaj olej i marchewkę.", "Wmieszaj mąkę z przyprawami.", "Piecz 40 minut w 175°C."] },
  { id: 194, title: "Biszkopt z galaretką", category: "ciasta", age: "seniorzy", time: 60,
    ingredients: ["4 jajka", "120 g cukru", "120 g mąki", "2 galaretki", "owoce"],
    steps: ["Upiecz biszkopt.", "Ułóż owoce na wierzchu.", "Przygotuj galaretkę.", "Zalej biszkopt galaretką.", "Schłódź do stężenia."] },
  { id: 195, title: "Sernik na kruchym spodzie", category: "ciasta", age: "seniorzy", time: 90,
    ingredients: ["spód kruchy", "800 g twarogu", "150 g cukru", "4 jajka", "budyń", "skórka cytrynowa"],
    steps: ["Upiecz spód kruchy.", "Zmiksuj twaróg z cukrem i żółtkami.", "Dodaj budyń.", "Wmieszaj pianę z białek.", "Piecz 60 minut w 160°C."] },
  { id: 196, title: "Jabłecznik na biszkopcie", category: "ciasta", age: "seniorzy", time: 70,
    ingredients: ["4 jajka", "120 g cukru", "120 g mąki", "1 kg jabłek", "cynamon"],
    steps: ["Jabłka zetrzyj i poddusz.", "Upiecz biszkopt.", "Nałóż masę jabłkową.", "Posyp cynamonem.", "Schłódź przed podaniem."] },
  { id: 197, title: "Ciasto cytrynowe lekkie", category: "ciasta", age: "seniorzy", time: 55,
    ingredients: ["200 g mąki", "100 g cukru", "2 jajka", "100 ml oleju", "1 cytryna", "proszek do pieczenia"],
    steps: ["Ubij jajka z cukrem.", "Dodaj olej i sok z cytryny.", "Wmieszaj mąkę z proszkiem.", "Przelej do formy.", "Piecz 35 minut w 175°C."] },
  { id: 198, title: "Murzynek tradycyjny", category: "ciasta", age: "seniorzy", time: 60,
    ingredients: ["300 g mąki", "200 g cukru", "4 jajka", "200 g masła", "4 łyżki kakao", "200 ml mleka", "proszek do pieczenia"],
    steps: ["Roztop masło z kakao i mlekiem.", "Dodaj cukier i jajka.", "Wmieszaj mąkę z proszkiem.", "Przelej do formy.", "Piecz 40 minut w 180°C."] },
  { id: 199, title: "Placek ze śliwkami", category: "ciasta", age: "seniorzy", time: 70,
    ingredients: ["250 g mąki", "150 g cukru", "150 g masła", "3 jajka", "500 g śliwek", "cynamon", "proszek do pieczenia"],
    steps: ["Utrzyj masło z cukrem.", "Dodaj jajka.", "Wmieszaj mąkę z proszkiem.", "Wyłóż ciasto i ułóż śliwki.", "Posyp cynamonem i piecz 45 minut w 180°C."] },
  { id: 200, title: "Ciasto ucierane z jabłkami", category: "ciasta", age: "seniorzy", time: 65,
    ingredients: ["250 g mąki", "150 g cukru", "150 g masła", "3 jajka", "4 jabłka", "cynamon", "proszek do pieczenia"],
    steps: ["Utrzyj masło z cukrem.", "Dodaj jajka.", "Wmieszaj mąkę z proszkiem.", "Wyłóż ciasto i ułóż starte jabłka.", "Piecz 45 minut w 175°C."] },

  // ====================== ŚWIĘTA: WIELKANOC (16) ======================
  // category: "swieta", holiday: "wielkanoc", dish: rodzaj dania
  { id: 201, title: "Żurek wielkanocny z białą kiełbasą", category: "swieta", holiday: "wielkanoc", dish: "Zupa", age: "dorosli", time: 60,
    ingredients: ["500 ml zakwasu na żur", "300 g białej kiełbasy", "150 g boczku wędzonego", "1 l bulionu", "2 ząbki czosnku", "majeranek", "4 jajka na twardo", "śmietana"],
    steps: ["Ugotuj bulion z boczkiem i kiełbasą.", "Pokrój kiełbasę i wróć do garnka.", "Wlej zakwas i zagotuj.", "Dopraw czosnkiem i majerankiem, zabiel śmietaną.", "Podawaj z połówką jajka."] },
  { id: 202, title: "Biała kiełbasa pieczona z cebulą", category: "swieta", holiday: "wielkanoc", dish: "Danie główne", age: "dorosli", time: 50,
    ingredients: ["1 kg białej kiełbasy", "3 cebule", "2 łyżki majeranku", "2 łyżki musztardy", "olej", "pieprz"],
    steps: ["Kiełbasę ponacinaj.", "Ułóż w naczyniu z pokrojoną cebulą.", "Posmaruj musztardą i posyp majerankiem.", "Piecz 35 minut w 180°C.", "Podawaj z chrzanem i pieczywem."] },
  { id: 203, title: "Jajka faszerowane pieczarkami", category: "swieta", holiday: "wielkanoc", dish: "Przystawka", age: "mlodzi", time: 30,
    ingredients: ["6 jajek", "200 g pieczarek", "1 cebula", "2 łyżki majonezu", "szczypiorek", "sól, pieprz", "bułka tarta"],
    steps: ["Ugotuj jajka na twardo i przekrój.", "Wyjmij żółtka.", "Podsmaż pieczarki z cebulą.", "Wymieszaj z żółtkami i majonezem.", "Napełnij połówki i posyp szczypiorkiem."] },
  { id: 204, title: "Pasztet wielkanocny domowy", category: "swieta", holiday: "wielkanoc", dish: "Przystawka", age: "seniorzy", time: 120,
    ingredients: ["500 g mięsa wieprzowego", "300 g wątróbki", "200 g boczku", "2 cebule", "2 jajka", "bułka namoczona", "przyprawy: gałka, ziele, sól, pieprz"],
    steps: ["Ugotuj mięso z warzywami.", "Zmiel z wątróbką i bułką.", "Dodaj jajka i przyprawy.", "Przełóż do keksówki.", "Piecz 60 minut w 180°C i ostudź."] },
  { id: 205, title: "Schab pieczony ze śliwką", category: "swieta", holiday: "wielkanoc", dish: "Danie główne", age: "dorosli", time: 90,
    ingredients: ["1 kg schabu", "100 g śliwek suszonych", "3 ząbki czosnku", "majeranek", "sól, pieprz", "olej"],
    steps: ["Schab natnij i nadziej śliwkami.", "Natrzyj czosnkiem i przyprawami.", "Obsmaż na patelni.", "Piecz 60 minut w 180°C.", "Pokrój w plastry po ostudzeniu."] },
  { id: 206, title: "Ćwikła z chrzanem", category: "swieta", holiday: "wielkanoc", dish: "Dodatek", age: "seniorzy", time: 50,
    ingredients: ["4 buraki", "3 łyżki tartego chrzanu", "ocet", "cukier", "sól"],
    steps: ["Buraki ugotuj i obierz.", "Zetrzyj na drobnej tarce.", "Dodaj chrzan.", "Dopraw octem, cukrem i solą.", "Odstaw do lodówki na kilka godzin."] },
  { id: 207, title: "Sałatka jarzynowa wielkanocna", category: "swieta", holiday: "wielkanoc", dish: "Sałatka", age: "dorosli", time: 50,
    ingredients: ["3 marchewki", "1 pietruszka", "kawałek selera", "3 ziemniaki", "4 jajka", "groszek", "ogórki kiszone", "majonez"],
    steps: ["Ugotuj warzywa i jajka.", "Pokrój wszystko w drobną kostkę.", "Dodaj groszek i ogórki.", "Wymieszaj z majonezem.", "Dopraw i schłodź."] },
  { id: 208, title: "Babka wielkanocna drożdżowa", category: "swieta", holiday: "wielkanoc", dish: "Ciasto", age: "seniorzy", time: 120,
    ingredients: ["500 g mąki", "50 g drożdży", "200 ml mleka", "100 g cukru", "4 żółtka", "100 g masła", "rodzynki", "lukier"],
    steps: ["Przygotuj rozczyn z drożdży.", "Zagnieć ciasto i odstaw do wyrośnięcia.", "Dodaj rodzynki.", "Przełóż do formy i odstaw ponownie.", "Piecz 45 minut w 180°C, polej lukrem."] },
  { id: 209, title: "Mazurek kajmakowy", category: "swieta", holiday: "wielkanoc", dish: "Ciasto", age: "dzieci", time: 60,
    ingredients: ["300 g mąki", "200 g masła", "100 g cukru pudru", "2 żółtka", "1 puszka masy kajmakowej", "orzechy", "bakalie"],
    steps: ["Zagnieć kruche ciasto i schłodź.", "Wyłóż na blachę i upiecz na złoto.", "Po ostudzeniu rozsmaruj kajmak.", "Udekoruj orzechami i bakaliami.", "Pokrój na kawałki."] },
  { id: 210, title: "Sernik wielkanocny", category: "swieta", holiday: "wielkanoc", dish: "Ciasto", age: "mlodzi", time: 90,
    ingredients: ["1 kg twarogu", "200 g cukru", "5 jajek", "150 g masła", "budyń waniliowy", "skórka cytrynowa", "rodzynki"],
    steps: ["Zmiel twaróg.", "Utrzyj masło z cukrem i żółtkami.", "Dodaj twaróg, budyń i skórkę.", "Wmieszaj ubitą pianę i rodzynki.", "Piecz 70 minut w 160°C."] },
  { id: 211, title: "Pascha wielkanocna", category: "swieta", holiday: "wielkanoc", dish: "Deser", age: "dorosli", time: 40,
    ingredients: ["500 g twarogu tłustego", "150 g masła", "100 g cukru pudru", "2 żółtka", "100 g bakalii", "wanilia"],
    steps: ["Zmiel twaróg.", "Utrzyj masło z cukrem i żółtkami.", "Połącz z twarogiem i wanilią.", "Dodaj bakalie.", "Uformuj i schłodź kilka godzin."] },
  { id: 212, title: "Żurek w chlebie", category: "swieta", holiday: "wielkanoc", dish: "Zupa", age: "mlodzi", time: 60,
    ingredients: ["500 ml zakwasu", "300 g białej kiełbasy", "boczek", "bulion", "czosnek", "majeranek", "4 bochenki chleba", "jajka"],
    steps: ["Ugotuj żurek na bulionie z kiełbasą.", "Dopraw czosnkiem i majerankiem.", "Wydrąż bochenki chleba.", "Wlej żurek do chleba.", "Podawaj z jajkiem."] },
  { id: 213, title: "Jajka w sosie tatarskim", category: "swieta", holiday: "wielkanoc", dish: "Przystawka", age: "dorosli", time: 25,
    ingredients: ["6 jajek", "majonez", "ogórki konserwowe", "musztarda", "szczypiorek", "sól, pieprz"],
    steps: ["Ugotuj jajka i przekrój.", "Posiekaj ogórki.", "Wymieszaj majonez z musztardą i ogórkami.", "Polej jajka sosem.", "Posyp szczypiorkiem."] },
  { id: 214, title: "Zupa chrzanowa", category: "swieta", holiday: "wielkanoc", dish: "Zupa", age: "seniorzy", time: 45,
    ingredients: ["1 l bulionu", "3 łyżki tartego chrzanu", "200 ml śmietany", "biała kiełbasa", "jajka", "sól, pieprz"],
    steps: ["Zagotuj bulion z pokrojoną kiełbasą.", "Dodaj chrzan.", "Zabiel śmietaną.", "Dopraw do smaku.", "Podawaj z połówką jajka."] },
  { id: 215, title: "Babka piaskowa wielkanocna", category: "swieta", holiday: "wielkanoc", dish: "Ciasto", age: "dzieci", time: 70,
    ingredients: ["250 g masła", "200 g cukru", "5 jajek", "300 g mąki", "100 g mąki ziemniaczanej", "proszek do pieczenia", "cukier puder"],
    steps: ["Utrzyj masło z cukrem.", "Dodawaj jajka.", "Wmieszaj mąki z proszkiem.", "Przelej do formy.", "Piecz 55 minut w 170°C, posyp cukrem pudrem."] },
  { id: 216, title: "Sałatka z jajek i szczypiorku", category: "swieta", holiday: "wielkanoc", dish: "Przystawka", age: "seniorzy", time: 20,
    ingredients: ["5 jajek", "pęczek szczypiorku", "majonez", "musztarda", "sól, pieprz"],
    steps: ["Ugotuj jajka na twardo.", "Pokrój w kostkę.", "Posiekaj szczypiorek.", "Wymieszaj majonez z musztardą.", "Połącz i dopraw."] },

  // ====================== ŚWIĘTA: BOŻE NARODZENIE (16) ======================
  // category: "swieta", holiday: "boze-narodzenie", dish: rodzaj dania
  { id: 217, title: "Barszcz czerwony wigilijny z uszkami", category: "swieta", holiday: "boze-narodzenie", dish: "Zupa", age: "dorosli", time: 90,
    ingredients: ["1 kg buraków", "bulion warzywny", "grzyby suszone", "czosnek", "majeranek", "kwasek lub ocet", "uszka z grzybami", "sól, pieprz"],
    steps: ["Ugotuj wywar z buraków i grzybów.", "Przecedź barszcz.", "Dopraw czosnkiem, majerankiem i kwaskiem.", "Ugotuj uszka osobno.", "Podawaj barszcz z uszkami."] },
  { id: 218, title: "Uszka z grzybami", category: "swieta", holiday: "boze-narodzenie", dish: "Dodatek", age: "mlodzi", time: 90,
    ingredients: ["300 g mąki", "1 jajko", "ciepła woda", "50 g grzybów suszonych", "1 cebula", "sól, pieprz"],
    steps: ["Zagnieć ciasto z mąki, jajka i wody.", "Namocz i ugotuj grzyby, posiekaj z cebulą.", "Rozwałkuj ciasto i wytnij kwadraty.", "Nałóż farsz i zlep uszka.", "Gotuj do wypłynięcia."] },
  { id: 219, title: "Pierogi z kapustą i grzybami", category: "swieta", holiday: "boze-narodzenie", dish: "Danie główne", age: "dorosli", time: 90,
    ingredients: ["500 g mąki", "1 jajko", "ciepła woda", "500 g kapusty kiszonej", "50 g grzybów suszonych", "1 cebula", "sól, pieprz"],
    steps: ["Zagnieć ciasto pierogowe.", "Uduś kapustę z grzybami i cebulą.", "Rozwałkuj ciasto i wytnij krążki.", "Nałóż farsz i zlep pierogi.", "Gotuj do wypłynięcia."] },
  { id: 220, title: "Kapusta z grochem", category: "swieta", holiday: "boze-narodzenie", dish: "Danie główne", age: "seniorzy", time: 60,
    ingredients: ["500 g kapusty kiszonej", "250 g grochu łuskanego", "1 cebula", "olej", "kminek", "sól, pieprz"],
    steps: ["Namocz i ugotuj groch.", "Udus kapustę do miękkości.", "Podsmaż cebulę.", "Połącz kapustę z grochem i cebulą.", "Dopraw kminkiem, solą i pieprzem."] },
  { id: 221, title: "Karp smażony", category: "swieta", holiday: "boze-narodzenie", dish: "Danie główne", age: "dorosli", time: 40,
    ingredients: ["4 dzwonka karpia", "mąka", "2 jajka", "bułka tarta", "sól, pieprz", "cytryna", "olej"],
    steps: ["Karpia natrzyj solą i pieprzem, skrop cytryną.", "Obtocz w mące, jajku i bułce.", "Smaż na rozgrzanym oleju na złoto.", "Osącz na ręczniku.", "Podawaj z cytryną."] },
  { id: 222, title: "Karp w galarecie", category: "swieta", holiday: "boze-narodzenie", dish: "Przystawka", age: "seniorzy", time: 120,
    ingredients: ["1 karp", "2 marchewki", "1 pietruszka", "1 cebula", "żelatyna", "ziele angielskie", "liść laurowy", "sól, pieprz"],
    steps: ["Ugotuj wywar z warzyw i przypraw.", "Ugotuj w nim kawałki karpia.", "Ułóż rybę i warzywa w naczyniu.", "Dodaj żelatynę do wywaru i zalej rybę.", "Schłódź do stężenia."] },
  { id: 223, title: "Śledzie w oleju z cebulą", category: "swieta", holiday: "boze-narodzenie", dish: "Przystawka", age: "dorosli", time: 30,
    ingredients: ["400 g płatów śledziowych", "2 cebule", "olej", "ziele angielskie", "liść laurowy", "pieprz"],
    steps: ["Wymocz śledzie i pokrój.", "Pokrój cebulę w piórka.", "Układaj warstwami śledzie i cebulę.", "Zalej olejem, dodaj przyprawy.", "Odstaw do lodówki na dobę."] },
  { id: 224, title: "Śledzie w śmietanie z jabłkiem", category: "swieta", holiday: "boze-narodzenie", dish: "Przystawka", age: "seniorzy", time: 30,
    ingredients: ["400 g płatów śledziowych", "200 ml śmietany", "1 jabłko", "1 cebula", "pieprz", "szczypta cukru"],
    steps: ["Wymocz śledzie i pokrój.", "Zetrzyj jabłko, posiekaj cebulę.", "Wymieszaj ze śmietaną.", "Połącz ze śledziami.", "Schłódź przed podaniem."] },
  { id: 225, title: "Zupa grzybowa wigilijna", category: "swieta", holiday: "boze-narodzenie", dish: "Zupa", age: "dorosli", time: 70,
    ingredients: ["100 g grzybów suszonych", "1 l bulionu warzywnego", "1 marchewka", "1 cebula", "200 ml śmietany", "łazanki", "sól, pieprz"],
    steps: ["Namocz grzyby.", "Ugotuj je w bulionie z warzywami.", "Pokrój grzyby i wróć do garnka.", "Zabiel śmietaną i dopraw.", "Podawaj z łazankami."] },
  { id: 226, title: "Makowiec tradycyjny", category: "swieta", holiday: "boze-narodzenie", dish: "Ciasto", age: "seniorzy", time: 120,
    ingredients: ["ciasto drożdżowe (mąka, drożdże, mleko, jajka, masło)", "500 g masy makowej", "bakalie", "lukier"],
    steps: ["Przygotuj ciasto drożdżowe i pozwól wyrosnąć.", "Rozwałkuj i nałóż masę makową.", "Zwiń ciasno roladę.", "Piecz 50 minut w 180°C.", "Polej lukrem po ostudzeniu."] },
  { id: 227, title: "Piernik staropolski świąteczny", category: "swieta", holiday: "boze-narodzenie", dish: "Ciasto", age: "dorosli", time: 90,
    ingredients: ["500 g mąki", "300 g miodu", "150 g cukru", "2 jajka", "przyprawa korzenna", "soda", "powidła śliwkowe", "polewa czekoladowa"],
    steps: ["Podgrzej miód z cukrem.", "Wymieszaj z mąką, jajkami i przyprawami.", "Odstaw ciasto na kilka dni.", "Upiecz blaty i przełóż powidłami.", "Oblej polewą czekoladową."] },
  { id: 228, title: "Kutia", category: "swieta", holiday: "boze-narodzenie", dish: "Deser", age: "seniorzy", time: 60,
    ingredients: ["200 g pszenicy", "150 g maku", "100 g miodu", "rodzynki", "orzechy", "bakalie"],
    steps: ["Ugotuj pszenicę do miękkości.", "Sparz i zmiel mak.", "Połącz pszenicę z makiem.", "Dodaj miód, orzechy i bakalie.", "Wymieszaj i schłódź."] },
  { id: 229, title: "Kompot z suszu", category: "swieta", holiday: "boze-narodzenie", dish: "Napój", age: "dorosli", time: 60,
    ingredients: ["300 g owoców suszonych", "1,5 l wody", "cukier", "goździki", "cynamon"],
    steps: ["Owoce zalej wodą.", "Dodaj przyprawy.", "Gotuj na małym ogniu 40 minut.", "Dosłódź do smaku.", "Podawaj ciepły lub schłodzony."] },
  { id: 230, title: "Bigos wigilijny", category: "swieta", holiday: "boze-narodzenie", dish: "Danie główne", age: "dorosli", time: 150,
    ingredients: ["1 kg kapusty kiszonej", "50 g grzybów suszonych", "śliwki suszone", "1 cebula", "koncentrat pomidorowy", "liść laurowy, ziele angielskie", "olej"],
    steps: ["Udus kapustę z namoczonymi grzybami.", "Podsmaż cebulę i dodaj.", "Dorzuć śliwki i koncentrat.", "Dopraw i duś kilka godzin.", "Najlepszy odgrzewany następnego dnia."] },
  { id: 231, title: "Pierniczki świąteczne", category: "swieta", holiday: "boze-narodzenie", dish: "Ciasto", age: "dzieci", time: 50,
    ingredients: ["400 g mąki", "150 g miodu", "100 g cukru", "1 jajko", "przyprawa korzenna", "soda", "lukier do dekoracji"],
    steps: ["Podgrzej miód z cukrem.", "Wymieszaj z mąką, jajkiem i przyprawami.", "Zagnieć ciasto i schłódź.", "Wykrawaj świąteczne kształty.", "Piecz 10 minut w 180°C i udekoruj lukrem."] },
  { id: 232, title: "Sałatka śledziowa świąteczna", category: "swieta", holiday: "boze-narodzenie", dish: "Sałatka", age: "dorosli", time: 30,
    ingredients: ["300 g śledzi", "2 jabłka", "2 jajka", "1 cebula", "ogórki kiszone", "majonez", "sól, pieprz"],
    steps: ["Pokrój śledzie w kawałki.", "Ugotuj i pokrój jajka.", "Zetrzyj jabłka, posiekaj cebulę i ogórki.", "Wymieszaj z majonezem.", "Dopraw i schłódź."] },
];

